--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
------------------------------------------------------------------------------------------------------]]

DRONE_COMBAT_RANGE = math.pow(25,2)
DRONE_COMBAT_RANGE = 

--[[----------------------------------------------------------------------------------------------------
	Utilities
------------------------------------------------------------------------------------------------------]]
function distance_xz_sqr(a,b)
	return a:position():distance_to_xz_sqr(b:position())
end

function firing_line_of_sight_clear(npc,obj)
	if (npc and obj) then
		local pos = utils_obj.safe_bone_pos(npc,"bip01_spine2")
		local dir = vector():sub(obj:center(),pos):normalize()
		local ray = ray_pick(pos,dir,100,3,npc)
		if (ray:query()) then
			local who = ray:get_object()
			if (who and (who:id() == obj:id())) then
				return true
			end
		end
	end
	return false
end

function validate(npc,vid)
	if (vid and vid < 4294967295 and npc:accessible(vid)) then 
		return (db.used_level_vertex_ids[vid] == nil) or (db.used_level_vertex_ids[vid] == npc:id())
	end 
	return false
end 

function best_enemy_drone(npc)
	local o = nil
	local d = DRONE_COMBAT_RANGE
	for oid,obj in pairs(db.drone_objects) do
		local dis = distance_xz_sqr(npc,obj)
		if (obj:alive() and obj:get_car():IsActiveEngine() and (d > dis)) then
			---[[
			if (true) then
				o = obj
				d = dis
			end
			--]]
			local mem = DRONE_MGR:StorageById(oid)
			if (mem and mem.owner_actor) and (npc:relation(db.actor) == game_object.enemy) then
				o = obj
				d = dis
			end
		end
	end
	return o
end

function can_npc_fight_drone(npc,obj)
	-- Using holder.
	if (npc:get_attached_vehicle()) then
		return false
	end
	-- Prioritize creature enemies if seeing them or they are closer.
	local ene = npc:best_enemy()
	if (ene) then
		if (npc:see(ene)) then
			return false
		end
		if (distance_xz_sqr(npc,ene) < distance_xz_sqr(npc,obj)) then
			return false
		end
	end
	return true
end

--[[----------------------------------------------------------------------------------------------------
	Main
------------------------------------------------------------------------------------------------------]]
function on_npc_vs_heli_eva(self,heli)
	if (self.mod_flags) then
		return
	end
	
	local obj = best_enemy_drone(self.object)
	if (obj and can_npc_fight_drone(self.object,obj)) then
		self.ret_value = true
		self.mod_flags = URB_TAC:Name()
	end
end

function on_npc_vs_heli_act(self)
	if (self.st.mod_flags ~= URB_TAC:Name()) then
		return
	end
	self.ret_value = false

	local obj = best_enemy_drone(self.object)
	if not (obj) then
		return
	end
	
	local npc = self.object
	if (npc:path_type() ~= game_object.level_path) then
		npc:set_path_type(game_object.level_path)
	end
	
	local see = firing_line_of_sight_clear(npc,obj)
	local dir = vector():sub(obj:center(),utils_obj.safe_bone_pos(npc,"bip01_r_finger02"))
	
	if (self.st.vid) then
		-- Move to cover.
		if (npc:level_vertex_id() ~= self.st.vid) then
			local new_state = see and "raid_fire" or "raid"
			state_mgr.set_state(npc,new_state,nil,nil,{look_dir = dir},{fast_set = true})
			axr_npc_vs_heli.lmove(npc,self.st.vid,self.st)
			return
		end
		
		-- Stay at cover.
		local new_state = see and "threat_fire" or "threat"
		state_mgr.set_state(npc,new_state,nil,nil,{look_dir = dir},{fast_set = true})
		
		self.st.__keep_point_until = self.st.__keep_point_until or (time_global() + math.random(3000,8000))
		if (self.st.__keep_point_until > time_global()) then
			return
		end
		-- Change cover.
		self.st.__keep_point_until = nil
		db.used_level_vertex_ids[self.st.vid] = nil
		self.st.vid = nil
	end
	
	if (self:try_go_cover(npc,obj:position(),10) == nil) then
		self:try_to_strafe(npc)
	end
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	RegisterScriptCallback("on_npc_vs_heli_eva",on_npc_vs_heli_eva)
	RegisterScriptCallback("on_npc_vs_heli_act",on_npc_vs_heli_act)
end