--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
	To do:
Implement inventory for CCar.
Make attachments to be inventory items instead.
Then we can transfer item in and out of CCar and only have to store item id.
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

_G.AddScriptCallback("drone_on_net")
_G.AddScriptCallback("drone_on_death")

--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
_G.DRONE_MGR = nil

class "CDroneManager"
function CDroneManager:__init()
	self.DRONE_STORAGE = {}
	
	self.cfg_item_to_object = {}
	self.cfg_object_to_item = {}
	
	do
		local ini = ini_file([[items\settings\deploy.ltx]])
		if (ini:section_exist("drones")) then
			for idx,val in pairs(utils_data.collect_section(ini,"drones",true)) do
				if (ini_sys:section_exist(idx) and ini_sys:section_exist(val) and self:IsDrone(val)) then
					self.cfg_item_to_object[idx] = val
					self.cfg_object_to_item[val] = idx
				else
					DEBUG("Wrong parameters [%s] %s",idx,val)
				end
			end
		end
	end
	
	self.cfg_attachments = {}
	self.cfg_drone_attachment_data = {}
	do
		local ini = ini_file([[misc\drone_attachments.ltx]])
		for idx,val in pairs(utils_data.collect_section(ini,"attachments",true)) do
			local tmp = val and str_explode(val,":")
			local kind = tmp and tmp[1]
			local sec = tmp and tmp[2]
			if (kind and sec and ini_sys:section_exist(idx) and ini_sys:section_exist(sec)) then
				self.cfg_attachments[idx] = {}
				self.cfg_attachments[idx].kind = kind
				self.cfg_attachments[idx].sec = sec
			else
				DEBUG("Wrong parameters [%s] %s",idx,val)
			end
		end
	end
	
	RegisterScriptCallback("save_state",self)
	RegisterScriptCallback("load_state",self)
	RegisterScriptCallback("server_entity_on_register",self)
	RegisterScriptCallback("server_entity_on_unregister",self)
	RegisterScriptCallback("actor_on_first_update",self)
	RegisterScriptCallback("actor_on_attach_vehicle",self)
	RegisterScriptCallback("actor_on_detach_vehicle",self)
	
	RegisterScriptCallback("map_spot_menu_add_property",self)
	RegisterScriptCallback("map_spot_menu_property_clicked",self)
	
	self.drone_script_callback_registered = false
end

function CDroneManager:save_state(m_data)
	m_data.GT_DRONE_STORAGE = self.DRONE_STORAGE
end

function CDroneManager:load_state(m_data)
	self.DRONE_STORAGE = m_data.GT_DRONE_STORAGE or {}
end

function CDroneManager:actor_on_first_update()
--[[
	for idx=#self.DRONE_ACT_OWN,1,-1 do
		local id = self.DRONE_ACT_OWN[idx]
		local se = id and alife_object(id)
		if (se) then
			if not (simulation_objects.is_on_the_actor_level(se)) then
				if (self:IsDrone(se:section_name())) then
					DEBUG("Release drone for not in actor level [%s]",se:name())
					alife_release(se)
				else
					DEBUG("ERROR: object invalid [%s]",se:name())
					self:ActorOwnDel(se.id)
				end
			end
		else
			DEBUG("ERROR: object does not exist")
			self:ActorOwnDel(se.id)
		end
	end
--]]
end

function CDroneManager:server_entity_on_register(se,flag)
	if (flag == "se_car") and (self:IsDrone(se:section_name())) then
		if (self.DRONE_STORAGE[se.id] == nil) then
			self.DRONE_STORAGE[se.id] = {}
		end
		DEBUG("server_entity_on_register(%s)",se:name())
	end
end

function CDroneManager:server_entity_on_unregister(se,flag)
	if (flag == "se_car") and (self:IsDrone(se:section_name())) then
		DEBUG("server_entity_on_unregister(%s)",se:name())
		self.DRONE_STORAGE[se.id] = nil
	end
end

function CDroneManager:actor_on_attach_vehicle(obj)
	if (obj and self:IsDrone(obj:section())) then
		if (self.drone_script_callback_registered ~= true) then
			self.drone_script_callback_registered = true
			RegisterScriptCallback("on_key_press",on_key_press)
		end
	end
end

function CDroneManager:actor_on_detach_vehicle(obj)
	if (obj and self:IsDrone(obj:section())) then
		if (self.drone_script_callback_registered == true) then
			self.drone_script_callback_registered = false
			UnregisterScriptCallback("on_key_press",on_key_press)
		end
	end
end

function CDroneManager:IsDrone(sec)
	return sec and (SYS_GetParam(0,sec,"kind") == "v_drone") and true or false
end

function CDroneManager:ItemToObject(sec)
	return sec and self.cfg_item_to_object[sec]
end

function CDroneManager:ObjectToItem(sec)
	return sec and self.cfg_object_to_item[sec]
end

function CDroneManager:StorageById(oid)
	return oid and self.DRONE_STORAGE[oid]
end

function CDroneManager:StorageCopy(src_id,dst_id)
	local sec = self:GetAttachmentSection(src_id)
	self:SetAttachmentSection(dst_id,sec)
end

function CDroneManager:Create(prs,owner_actor)
	local sec = prs and prs.sec
	local pos = prs and prs.pos
	local vid = prs and prs.vid
	local gid = prs and prs.gid
	local ang = prs and prs.ang
	local itm = prs and prs.itm
	if (sec and pos and vid and gid and ang and self:IsDrone(sec)) then
		local se = alife_create(sec,pos,vid,gid)
		se.angle = vector():set(ang.y,ang.x,ang.z)
		if (itm) then
			self:StorageCopy(itm:id(),se.id)
		end
		if (owner_actor) then
			self:StorageById(se.id).owner_actor = true
		end
		return true
	end
	DEBUG("Wrong parameters %s %s %s %s %s",sec,pos,vid,gid,ang)
	return false
end

function CDroneManager:Attachments()
	return self.cfg_attachments
end

function CDroneManager:AttachmentData(sec)
	if (self.cfg_drone_attachment_data[sec] == nil) then
		local lst = {}
		local str = sec and SYS_GetParam(0,sec,"attachment_data")
		if (str) then
			for _,val in ipairs(str_explode(str,",")) do
				if (self.cfg_attachments[val]) then
					lst[#lst+1] = val
				else
					DEBUG("[%s] attachment does not exist [%s]",sec,val)
				end
			end
		end
		self.cfg_drone_attachment_data[sec] = lst
	end
	return self.cfg_drone_attachment_data[sec]
end

function CDroneManager:GetAttachmentSection(oid)
	return se_load_var(oid,nil,"drone_attachment_section")
end

function CDroneManager:SetAttachmentSection(oid,sec)
	se_save_var(oid,nil,"drone_attachment_section",sec)
end

function CDroneManager:map_spot_menu_add_property(property_ui,oid,lvl)
	local obj = db.drones[oid]
	if (obj) then
		property_ui:AddItem(GT("drone_pda_cmd_control"))
	end
end

function CDroneManager:map_spot_menu_property_clicked(property_ui,oid,lvl,sec)
	local obj = db.drones[oid]
	if (obj) then
		if (sec == GT("drone_pda_cmd_control")) then
			db.actor:activate_slot(0)
			if (obj:binded_object()) then
				obj:binded_object():TakeControl()
			end
		end
	end
end

--[[----------------------------------------------------------------------------------------------------
	Storage
------------------------------------------------------------------------------------------------------]]
db.drones = {}

function add_drone(obj)
	db.drones[obj:id()] = obj
end

function del_drone(obj)
	db.drones[obj:id()] = nil
end

function on_before_hit(obj,shit,bone_id)
	return true
end

function on_before_use(obj,cam_pos,cam_dir,act_pos)
	CreateTimeEvent(obj:id(),"on_before_use",0,pick_up_time_event,obj:id())
	return false
end

function pick_up_time_event(oid)
	local obj = URB_TAC:object_by_id(oid)
	local sec = obj and DRONE_MGR:ObjectToItem(obj:section())
	if (sec) then
		local se = alife_create_item(sec,db.actor)
		DRONE_MGR:StorageCopy(obj:id(),se.id)
	end
	return true
end

--[[----------------------------------------------------------------------------------------------------
	Keys
------------------------------------------------------------------------------------------------------]]
KEY_DETONATE_DEF = DIK_keys.DIK_J
KEY_DETONATE = KEY_DETONATE_DEF

function on_key_press(dik)
	if (dik == KEY_DETONATE) then
		local obj = db.actor:get_attached_vehicle()
		if (obj and DRONE_MGR:IsDrone(obj:section())) then
			if (obj:binded_object()) then
				obj:binded_object():ExplosiveDetonate(db.actor)
			end
		end
	end
end

--------------------------------------------------------------------------------------------------------
--[[
local DRONE_CONTROLLER_MAX_RANGE = 200
local DRONE_CONTROLLER_WARNING_PPE = 52000

function drone_controller_warning_ppe_update(flag)
	if (flag) then
		level.add_pp_effector("radiation.ppe",DRONE_CONTROLLER_WARNING_PPE,true)
	else
		level.remove_pp_effector(DRONE_CONTROLLER_WARNING_PPE)
	end
end

function actor_on_update()
	local obj = db.actor:get_attached_vehicle()
	if (obj and DRONE_MGR:IsDrone(obj:section())) then
		local range = math.pow(DRONE_CONTROLLER_MAX_RANGE * 0.9,2)
		if (db.actor:position():distance_to_sqr(obj:position()) > range) then
			drone_controller_warning_ppe_update(true)
		else
			drone_controller_warning_ppe_update(false)
		end
	end
end
--]]
--[[----------------------------------------------------------------------------------------------------
	Binder
------------------------------------------------------------------------------------------------------]]
function init(obj)
	obj:bind_object(CDroneBinder(obj))
end

class "CDroneBinder" (object_binder)
function CDroneBinder:__init(obj) super(obj)
	db.storage[self.object:id()] = {}
	self.oid = self.object:id()
	self.car = self.object:get_car()
	self.mem = DRONE_MGR:StorageById(self.oid)
	
	self.attachment_bone = SYS_GetParam(0,self.object:section(),"attachment_bone")
	self.map_spot = SYS_GetParam(0,self.object:section(),"map_spot")
	
	self.fc_delta = nil
	self.fc_timer = nil
	self.fc_delay = 100
	self.object:set_fastcall(self.update,self)
end

function CDroneBinder:update(delta)
	object_binder.update(self,delta)
	local t = time_global()
	if (self.fc_timer and (self.fc_timer > t)) then
		return
	end
	self.fc_delta = self.fc_timer and (t - self.fc_timer + self.fc_delay) or 0
	self.fc_timer = t + self.fc_delay
end

function CDroneBinder:AttachmentUpdate()
	local bid = self.attachment_bone and self.object:bone_id(self.attachment_bone)
	if (bid and bid ~= 65535) then
		local k = self:AttachmentData()
		if (k) then
			if (self.object:get_attachment("payload") == nil) then
				self.object:add_attachment("payload",k.visual):set_parent_bone(bid)
				self.car:SetFlyWeightAdd(k.weight)
			end
		else
			if (self.object:get_attachment("payload")) then
				self.object:remove_attachment("payload")
				self.car:SetFlyWeightAdd(0)
			end
		end
	else
		DEBUG("[%s] wrong parameters bone_name:%s bid:%s",self.object:name(),bone_name,bid)
	end
end

function CDroneBinder:AttachmentData()
	local sec = self:ExplosiveSection()
	if (sec) then
		local visual = SYS_GetParam(0,sec,"visual")
		local weight = SYS_GetParam(2,sec,"attachment_weight",0)
		if (visual and weight) then
			local t = {}
			t.visual = visual
			t.weight = weight
			return t
		end
	end
end

function CDroneBinder:CanTakeControl()
	if not (self.object:alive()) then
		return false
	end
	local d = math.pow(200,2)
	if not (db.actor:position():distance_to_sqr(self.object:position()) < d) then
		return false
	end
	return true
end

function CDroneBinder:TakeControl()
	if (self.object:alive()) then
		local obj = db.actor:get_attached_vehicle()
		if (obj) then
			if (obj:id() == self.oid) then
				return
			end
			db.actor:detach_vehicle(true)
		end
		db.actor:attach_vehicle(self.object,true)
	end
end

function CDroneBinder:ExplosiveDetonate(who)
	local sec = self:ExplosiveSection()
	if (sec and self.object:alive()) then
		DRONE_MGR:SetAttachmentSection(self.object:id(),nil)
		self.car:LoadExplosiveSection(sec)
		self.car:SetInitiator(who and who:id() or self.oid)
		self.object:kill(who)
	end
end

function CDroneBinder:ExplosiveSection()
	local sec = DRONE_MGR:GetAttachmentSection(self.object:id())
	local tmp = DRONE_MGR:Attachments()[sec]
	if (tmp and (tmp.kind == "exp")) then
		return tmp.sec
	end
end

function CDroneBinder:UpdateMapSpot(enable)
	level.map_remove_all_object_spots(self.oid)
	if not (enable) then
		return
	end
	
	if not (self.object:alive() and self.map_spot and self.mem.owner_actor) then
		return
	end
	
	if (level.map_has_object_spot(self.oid,self.map_spot) == 0) then
		local txt = ui_item.get_sec_name(self.object:section())
		local sec = DRONE_MGR:GetAttachmentSection(self.object:id())
		if (sec) then
			txt = txt .. "\n" .. strformat(GT("drone_pda_info_attach"),ui_item.get_sec_name(sec))
		end
		level.map_add_object_spot(self.oid,self.map_spot,txt)
	end
end

----------------------------------------------------------------------------------------------------
function CDroneBinder:reload(section)
	object_binder.reload(self,section)
end

function CDroneBinder:reinit()
	object_binder.reinit(self)
	db.storage[self.object:id()] = db.storage[self.object:id()] or {}
	self.st = db.storage[self.object:id()]
end

function CDroneBinder:net_spawn(se_abstract)
	if not (object_binder.net_spawn(self,se_abstract)) then
		return false
	end
	db.add_obj(self.object)
	add_drone(self.object)
	self.object:set_callback(callback.death,self.death_callback,self)
	
	self:AttachmentUpdate()
	self:UpdateMapSpot(true)
	
	CreateTimeEvent(self.oid,"after_net_spawn",0,self.after_net_spawn,self)
	SendScriptCallback("drone_on_net",self.object,true)
	return true
end

function CDroneBinder:net_destroy()
	self:UpdateMapSpot(false)
	
	SendScriptCallback("drone_on_net",self.object,false)
	db.del_obj(self.object)
	del_drone(self.object)
	self.object:set_callback(callback.death,nil)
	object_binder.net_destroy(self)
end

function CDroneBinder:death_callback(obj,who)
	self:RemoveMapSpot()
	SendScriptCallback("drone_on_death",obj,who)
end

function CDroneBinder:net_save_relevant()
	return true
end

function CDroneBinder:save(packet)
	object_binder.save(self,packet)
	set_save_marker(packet,"save",false,"physics_binder")
	set_save_marker(packet,"save",true,"physics_binder")
	
	if (self.mem) then
		self.mem.engine_on = self.car:IsActiveEngine()
	end
end

function CDroneBinder:load(packet)
	object_binder.load(self,packet)
	set_save_marker(packet,"load",false,"physics_binder")
	set_save_marker(packet,"load",true,"physics_binder")
end

function CDroneBinder:after_net_spawn()
	if (self.mem) then
		if (self.mem.engine_on) then
			self.mem.engine_on = nil
			self.car:StartEngine()
		end
	end
	return true
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	_G.DRONE_MGR = CDroneManager()
end

function DEBUG(str,...)
	local func = debug.getinfo(2,"S").source
	local line = debug.getinfo(2,"l").currentline
	func = string.sub(func,#func - string.find(string.reverse(func),"\\") + 2,#func)
	local p = {...}
	if (p and (#p ~= 0)) then
		printf(string.format("[GhenTuong] %s:%s | %s",tostring(func),tostring(line),str),...)
	else
		printf(string.format("[GhenTuong] %s:%s | ",tostring(func),tostring(line)) .. "%s",str)
	end
end
