--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

--[[----------------------------------------------------------------------------------------------------
	Main
------------------------------------------------------------------------------------------------------]]
function drone_deploy_desc(obj)
	return GT("drone_item_deploy")
end

function drone_deploy_func(obj)
	if (deploy_condition()) then
		hud_deploy_active(obj)
	end
end

function drone_detach_desc(obj)
	local sec = DRONE_MGR:GetAttachmentSection(obj:id())
	if (sec) then
		return strformat(GT("drone_item_detach"),ui_item.get_sec_name(sec))
	end
end

function drone_detach_func(obj)
	local sec = DRONE_MGR:GetAttachmentSection(obj:id())
	if (sec) then
		alife_create_item(sec,db.actor)
		DRONE_MGR:SetAttachmentSection(obj:id(),nil)
	end
end

function ActorMenu_on_item_drag_drop(itm,obj,slot_from,slot_next)
	if not (slot_from == EDDListType.iActorBag and slot_next == EDDListType.iActorBag) then
        return
    end
	
	local itm_sec = itm:section()
	local obj_sec = obj:section()
	
	if not (DRONE_MGR:Attachments()[itm_sec] and DRONE_MGR:ItemToObject(obj_sec)) then
		DEBUG()
		return
	end
	
	if (DRONE_MGR:GetAttachmentSection(obj:id())) then
		DEBUG()
		return
	end
	
	local atm = parse_list(ini_sys,obj_sec,"attachment_data",true)
	if (atm and atm[itm_sec]) then
		DEBUG()
		DRONE_MGR:SetAttachmentSection(obj:id(),itm_sec)
		alife_release(itm)
	end
end

function deploy_condition()
	if not (db.actor:alive()) then
		return false
	end
	if (db.actor:get_attached_vehicle()) then
		return false
	end
	if (db.actor:is_talking()) then
		return false
	end
	if (IsMoveState("mcClimb")) then
		return false
	end
	return true
end

--[[----------------------------------------------------------------------------------------------------
	UIDeploy
------------------------------------------------------------------------------------------------------]]
HUD = nil

function hud_deploy_active(obj)
	if (HUD == nil) then
		HUD = UIDeploy(obj)
		get_hud():AddDialogToRender(HUD)
		RegisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_remove()
	if (HUD) then
		get_hud():RemoveDialogToRender(HUD)
		HUD = nil
		UnregisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_update()
	if (HUD) then
		HUD:Update(true)
	end
end

function on_key_press(dik)
	if (HUD) then
		HUD:OnKeyPress(dik)
	end
end

class "UIDeploy" (CUIScriptWnd)
function UIDeploy:__init(obj) super(obj)
	self:SetWndRect(Frect():set(0,0,1280,768))
	self:SetAutoDelete(true)
	
	self.oid = obj:id()
	self.sec = obj:section()
	self.vis = self:GetAttachmentVisual(obj)
	self.atm_name = "deploy_drone"
	self.dist_def = 1
	self.dist_max = 3
	
	self.radius_min = 0.5
	self.radius_max = 1.0
	self.height_min = -1.8
	self.height_max = 0.0
	
	self.exclusive_radius = 0.4
	self.exclusive_height = 0.05
	self.vec_up = vector():set(VEC_Y)
	self.vec_dw = vector():set(self.vec_up):invert()
	
	self.active = db.actor:active_slot()
	self.hiding = (self.active ~= 0) and true or false
	db.actor:activate_slot(0)
	hide_hud_inventory()
end

function UIDeploy:__finalize()
end

function UIDeploy:Update()
	CUIScriptWnd.Update(self)
	
	if not (main_hud_shown()) then
		return self:Close()
	end
	
	if not (deploy_condition()) then
		return self:Close()
	end
	
	if not (URB_TAC:object_by_id(self.oid)) then
		return self:Close()
	end
	
	if not (self.vis) then
		return self:Close()
	end
	
	if (self.hiding) then
		if (db.actor:active_slot() == 0) then
			self.hiding = false
		elseif (db.actor:active_slot() ~= self.active) then
			return self:Close()
		end
	else
		if (db.actor:active_slot() ~= 0) then
			return self:Close()
		end
	end
	
	self.pos = self:GetDeployPosition()
	
	if (self.pos) then
		if (level.get_attachment(self.atm_name) == nil) then
			level.add_attachment(self.atm_name,self.vis)
		end
		local atm = level.get_attachment(self.atm_name)
		if (atm) then
			atm:set_position(self.pos)
			local h = math.deg(device().cam_dir:getH())
			atm:set_rotation(h,0,0)
		end
	else
		if (level.get_attachment(self.atm_name)) then
			level.remove_attachment(self.atm_name)
		end
	end
	
	if (self:CheckDeployPosition()) then
		
	end
end

function UIDeploy:Deploy()
	if (self.hiding) then
		return
	end
	if (self:CheckDeployPosition() == false) then
		return
	end
	local atm = level.get_attachment(self.atm_name)
	local xfm = atm and atm:get_transform()
	if not (xfm) then
		return
	end
	local obj = URB_TAC:object_by_id(self.oid)
	local k = {}
	k.sec = DRONE_MGR:ItemToObject(obj:section())
	k.pos = vector():set(xfm.c)
	k.vid = db.actor:level_vertex_id()
	k.gid = db.actor:game_vertex_id()
	k.ang = xfm:getHPB()
	k.itm = obj
	if (DRONE_MGR:Create(k,true)) then
		itms_manager.play_item_sound(obj,0.75)
		news_manager.relocate_item(db.actor,"out",obj:section())
		alife_release(obj)
	end
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:GetAttachmentVisual(obj)
	local sec = obj and DRONE_MGR:ItemToObject(obj:section())
	return sec and SYS_GetParam(0,sec,"visual")
end

function UIDeploy:GetDeployPosition()
	local pos = device().cam_pos
	local dir = device().cam_dir
	if (dir:getP() > 0) then
		return
	end
	local ray = ray_pick(pos,dir,self.dist_max,2,db.actor)
	local vec = ray:query() and vector():mad(pos,dir,ray:get_distance())
	if (self:ValidatePosition(vec)) then
		return vec
	end
end

function UIDeploy:ValidatePosition(vec)
	if not (vec) then
		return false
	end
	local rds = device().cam_pos:distance_to_xz_sqr(vec)
	if (rds < math.pow(self.radius_min,2)) or (rds > math.pow(self.radius_max,2)) then
		return false
	end
	local tmp = vec.y - device().cam_pos.y
	if (tmp < self.height_min) or (tmp > self.height_max) then
		return false
	end
	return true
end

function UIDeploy:CheckDeployPosition()
	local atm = level.get_attachment(self.atm_name)
	local tmp = atm and vector():set(atm:get_transform().c)
	local pos = tmp and vector():mad(tmp,self.vec_up,self.exclusive_height)
	if not (pos) then
		return false
	end
	
	local function check(rds)
		local dir = vector():setHP(math.rad(rds*10),0):normalize()
		do
			local ray = ray_pick(pos,dir,self.exclusive_radius,3,db.actor)
			if (ray:query()) then
				return false
			end
		end
		local vec = vector():mad(pos,dir,self.exclusive_radius)
		do
			local ray = ray_pick(vec,self.vec_dw,self.exclusive_radius,3,db.actor)
			if (ray:query()) then
				if (ray:get_object()) then
					return false
				end
				if (ray:get_distance() > self.exclusive_height * 2) then
					return false
				end
			end
		end
		return true
	end
	
	for k=0,35 do
		if (check(k) == false) then
			return false
		end
	end
	return true
end

function UIDeploy:ResumeActive()
	if (self.active ~= 0) then
		db.actor:activate_slot(self.active)
	end
end

function UIDeploy:Cancel()
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:Close()
	if (level.get_attachment(self.atm_name)) then
		level.remove_attachment(self.atm_name)
	end
	hud_deploy_remove()
end

function UIDeploy:OnKeyPress(dik)
	if (dik == DIK_keys.MOUSE_1) then
		return self:Deploy()
	end
	if (dik == DIK_keys.MOUSE_2) then
		return self:Cancel()
	end
end

--[[----------------------------------------------------------------------------------------------------
	Callbacks
------------------------------------------------------------------------------------------------------]]
function on_show_hide()
	hud_deploy_update()
end

function actor_on_net_destroy()
	hud_deploy_remove()
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	RegisterScriptCallback("GUI_on_show",on_show_hide)
	RegisterScriptCallback("GUI_on_hide",on_show_hide)
	RegisterScriptCallback("actor_on_net_destroy",actor_on_net_destroy)
	
	RegisterScriptCallback("ActorMenu_on_item_drag_drop",ActorMenu_on_item_drag_drop)
end

function DEBUG(str,...)
	local func = debug.getinfo(2,"S").source
	local line = debug.getinfo(2,"l").currentline
	func = string.sub(func,#func - string.find(string.reverse(func),"\\") + 2,#func)
	local p = {...}
	if (p and (#p ~= 0)) then
		printf(string.format("[GhenTuong] %s:%s | %s",tostring(func),tostring(line),str),...)
	else
		printf(string.format("[GhenTuong] %s:%s | ",tostring(func),tostring(line)) .. "%s",str)
	end
end
