--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
------------------------------------------------------------------------------------------------------]]

local MATERIAL_NO_EXPLODE = {
	["material\\bush"] = true,
	["material\\water"] = true,
}

-- A little offset to make sure flame spites are spawned above ground.
local FLAME_OFFSET = vector():set(0.0,0.2,0.0)

local GRAVITY_HALF = 4.9

local FLAME_AMOUNT = 120

-- Limit the height to generate flame. Too low and too high to where the grenade hits.
local FLAME_HEIGHT_MAX = 0.5
local FLAME_HEIGHT_MIN = -50

--[[----------------------------------------------------------------------------------------------------
	Main
------------------------------------------------------------------------------------------------------]]
flame_objects = {}

function add_binded_object(obj)
	flame_objects[obj:id()] = obj
end

function del_binded_object(obj)
	flame_objects[obj:id()] = nil
end

function on_explode(obj,prs)
	if (prs.flag and not MATERIAL_NO_EXPLODE[prs.material]) then
		MGR:FlameCreate(obj,prs.position,prs.velocity)
		return
	end
	-- Failed to explode. Respawn the grenade.
	local sec = obj:section()
	local pos = vec_add(prs.position,FLAME_OFFSET)
	local vid = obj:level_vertex_id()
	local gid = obj:game_vertex_id()
	local ang = obj:angle()
	local vec = vector():set(prs.velocity.x,prs.velocity.y,prs.velocity.z)
	local itm = alife_create(sec,pos,vid,gid)
	itm.angle = vector():set(ang.y,ang.x,ang.z)
	CreateTimeEvent(itm.id,"grenade_flame_on_explode",0,on_item_drop_time_event,itm.id,pos)
end

function on_item_drop_time_event(oid,pos)
	local obj = URB_TAC:ObjectById(oid)
	if (obj) then
		SendScriptCallback("actor_on_item_drop",obj)
		obj:force_set_position(pos)
		URB_TAC:DEBUG("[%s] drop success.",obj:name())
		return true
	end
end

--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
MGR = nil

class "CFlameManager"
function CFlameManager:__init()
	self.FLAME_STORAGE = {}
	
	self.timer = 0
	
	RegisterScriptCallback("save_state",self)
	RegisterScriptCallback("load_state",self)
	--RegisterScriptCallback("actor_on_update",self)
	RegisterScriptCallback("actor_on_first_update",self)
end

function CFlameManager:save_state(m_data)
	m_data.GT_FLAME_STORAGE = self.FLAME_STORAGE
end

function CFlameManager:load_state(m_data)
	self.FLAME_STORAGE = m_data.GT_FLAME_STORAGE or {}
end

function CFlameManager:actor_on_first_update()
	for oid,var in pairs(self.FLAME_STORAGE) do
		local se = alife_object(oid)
		if (simulation_objects.is_on_the_actor_level(se) ~= true) then
			if (se) then
				alife_release(se)
			end
			self:FlameRemove(oid)
			URB_TAC:DEBUG("[%s] Release due to changing level.",se and se:name())
		end
	end
end

function CFlameManager:actor_on_update()
	if (self.timer and self.timer > time_global()) then
		return
	end
	self.timer = time_global() + 100
	for _,oid in ipairs(db.OnlineStalkers) do
		local npc = URB_TAC:ObjectById(oid)
		local who = npc and self:InFlame(npc)
		if (who) then
			self:ApplyBurnDamage(npc,who)
		end
	end
end

function CFlameManager:InFlame(npc)
	-- Try to get an owner who is still alive. Otherwise, let the npc hits himself.
	local pos = npc:position()
	local who = nil
	for oid,obj in pairs(flame_objects) do
		local var = self:FlameObject(oid)
		local vec = obj:position()
		if (var) and (vec.y < pos.y + 0.2) and (vec.y > pos.y - 1.5) then
			if (pos:distance_to_xz_sqr(vec) < math.pow(3,2)) then
				local ene = var.owner and URB_TAC:ObjectById(var.owner)
				if (who == nil) or (who:id() == npc:id()) then
					who = ene and IsStalker(ene) and ene:alive() and ene or npc
					if (who:id() ~= npc:id()) then
						return who
					end
				end
			end
		end
	end
	return who
end

function CFlameManager:ApplyBurnDamage(npc,who)
	local h = hit()
	h.type		= hit.light_burn
	h.power		= 0.01
	h.impulse	= 0
	h.direction	= vector():set(VEC_Y)
	h.draftsman	= who
	h:bone("bip01_spine")
	npc:hit(h)
end

function CFlameManager:FlameCreate(obj,pos,vel)
	local sec = SYS_GetParam(0,obj:section(),"on_explode_spawn")
	local rds = tonumber(SYS_GetParam(0,obj:section(),"flame_radius"))
	if not (sec and ini_sys:section_exist(sec) and rds) then
		URB_TAC:DEBUG("%s: obj:%s sec:%s rds:%s",URB_TAC:name(),obj:section(),sec,rds)
		assert(nil,URB_TAC:Name())
	end
	local vid = obj:level_vertex_id()
	local gid = obj:game_vertex_id()
	local se = alife_create(sec,pos,vid,gid)
	
	local dir = vector():set(vel):normalize():invert()
	local vec = vector():mad(pos,dir,0.1)
	local var = {}
	var.owner = obj:cast_Explosive():Initiator()
	var.timer = 60 * 1000
	var.delay = 60 * 1000
	var.flame = self:GenerateFlamePosition(vec,vel,rds,lim)
	self.FLAME_STORAGE[se.id] = var
end

function CFlameManager:FlameRemove(oid)
	self.FLAME_STORAGE[oid] = nil
end

function CFlameManager:FlameObject(oid)
	return self.FLAME_STORAGE[oid]
end

function CFlameManager:VectorToTable(v)
	local x = tonumber(v.x)
	local y = tonumber(v.y)
	local z = tonumber(v.z)
	if (x and y and z) then
		return {x = x,y = y,z = z}
	end
	URB_TAC:DEBUG("Wrong parameters: %s,%s,%s",x,y,z)
	assert(nil,URB_TAC:Name())
end

function CFlameManager:TableToVector(v)
	local x = tonumber(v.x)
	local y = tonumber(v.y)
	local z = tonumber(v.z)
	if (x and y and z) then
		return vector():set(x,y,z)
	end
	URB_TAC:DEBUG("Wrong parameters: %s,%s,%s",x,y,z)
	assert(nil,URB_TAC:Name())
end

function CFlameManager:GenerateFlamePosition(pos,vel,rds,lim)
	--[[
	
	--]]
	local tmp = {}
	for k=1,FLAME_AMOUNT do
		local r = math.random() * math.pi * 2
		local d = math.random() * rds
		local dir = self:ThrowVelocity(r,d,1)
		local vec = self:ThrowCast(pos,dir)
		if (vec and (vec:distance_to_sqr(pos) > 0.01)) then
			tmp[#tmp+1] = self:VectorToTable(vec)
		end
	end
	return tmp
end

function CFlameManager:ThrowCast(pos,vel)
	local src = vector():set(pos)
	local dst = vector():set(pos)
	for k=1,100 do
		src:set(dst)
		dst = self:TrajectoryPosition(pos,vel,k * 0.1)
		if (dst.y < pos.y + FLAME_HEIGHT_MIN) then
			-- Too low.
			break
		end
		if (dst.y > pos.y + 0.1) then
			-- Higher than where the grenade lands. Must have a clear LoS.
			local dir = vec_sub(dst,pos)
			local num = dir:magnitude()
			local ray = ray_pick(src,dir,num,2,nil)
			if (ray:query()) then
				break
			end
		end
		local dir = vec_sub(dst,src)
		local num = dir:magnitude()
		if (num > 0) then
			local ray = ray_pick(src,dir,num,2,nil)
			local tmp = ray:query() and ray:get_distance()
			if (tmp) then
				-- src -> dst hits a surface.
				if (dir.y > 0) then
					-- Is going up, dst is higher than src. Skip.
					break
				end
				local vec = vector():mad(src,dir:normalize(),tmp)
				if (vec.y > pos.y + FLAME_HEIGHT_MAX) then
					-- Is going down. But too high than where the grenade lands. Skip.
					break
				end
				return vec
			end
		end
	end
end

function CFlameManager:ThrowVelocity(r,d,t)
	-- Calculate the vector velocity to throw an object to arrive at p in t seconds.
	local p = vector():setHP(r,0):normalize():mul(d)
	local x = p.x / t
	local z = p.z / t
	local y = GRAVITY_HALF * t
	return vector():set(x,y,z)
end

function CFlameManager:TrajectoryPosition(p,v,t)
	-- Calculate the position of an object thrown from p with velocity v after t seconds.
	local m = vector():set(v.x,0,v.z):mul(t)
	m.y = (v.y * t) - (GRAVITY_HALF * math.pow(t,2))
	return vector():set(p):add(m)
end

--[[----------------------------------------------------------------------------------------------------
	CFlame
------------------------------------------------------------------------------------------------------]]

class "CFlame"
function CFlame:__init(idx,pos,str)
	self.idx = idx
	self.pos = pos
	self.ptc = particles_object(str)
	if (self.ptc == nil) then
		URB_TAC:DEBUG("Failed to load:%s",str)
		assert(nil,URB_TAC:Name())
	end
end

function CFlame:Update(flag)
	if (self.ptc == nil) then
		return
	end
	if (flag) then
		if (self.ptc:playing() ~= true) then
			self.ptc:play_at_pos(self.pos,false)
		end
		if (self.ptc:playing() == true) then
			self.ptc:move_to(self.pos,VEC_ZERO)
		end
	else
		if (self.ptc:playing()) then
			self.ptc:stop_deffered()
		end
	end
end

function CFlame:Remove()
	if (self.ptc) then
		self.ptc:stop()
		self.ptc = nil
	end
end

--[[----------------------------------------------------------------------------------------------------
	Binder
------------------------------------------------------------------------------------------------------]]
function init(obj)
	obj:bind_object(CFlameBinder(obj))
end

class "CFlameBinder" (object_binder)
function CFlameBinder:__init(obj) super(obj)
	db.storage[self.object:id()] = {}
	self.oid = self.object:id()
	
	local section = obj:section()
	
	self.ptc_blast_name = SYS_GetParam(0,section,"ptc_blast")
	self.ptc = particles_object(self.ptc_blast_name)
	if (self.ptc == nil) then
		URB_TAC:DEBUG("Failed to load:%s",self.ptc_blast_name)
		assert(nil,URB_TAC:Name())
	end
	
	self.snd_flame_name = SYS_GetParam(0,section,"snd_flame")
	self.snd = sound_object(self.snd_flame_name)
	if (self.snd == nil) then
		URB_TAC:DEBUG("Failed to load:%s",self.snd_flame_name)
		assert(nil,URB_TAC:Name())
	end
	
	self.ptc_flame_name = SYS_GetParam(0,section,"ptc_flame")
	self.flame = {}
	local var = MGR:FlameObject(self.oid)
	if (var and var.flame) then
		for idx=1,#var.flame do
			self.flame[idx] = CFlame(idx,MGR:TableToVector(var.flame[idx]),self.ptc_flame_name)
		end
	end
	
	self.fc_delta = nil
	self.fc_timer = nil
	self.fc_delay = 100
	self.object:set_fastcall(self.update,self)
end

function CFlameBinder:reload(section)
	object_binder.reload(self,section)
end

function CFlameBinder:reinit()
	object_binder.reinit(self)
	db.storage[self.object:id()] = db.storage[self.object:id()] or {}
	self.st = db.storage[self.object:id()]
end

function CFlameBinder:update(delta)
	object_binder.update(self,delta)
	if (self.fc_timer and (self.fc_timer > time_global())) then
		return
	end
	self.fc_delta = self.fc_timer and (time_global() - self.fc_timer + self.fc_delay) or 0
	self.fc_timer = time_global() + self.fc_delay
	
	local var = MGR:FlameObject(self.oid)
	if not (var and var.timer) then
		return self:Release()
	end
	
	var.timer = math.max(0,var.timer - self.fc_delta)
	if (var.timer == 0) then
		return self:Release()
	end
	
	if (self.ptc) then
		if (var.timer == var.delay) then
			self.ptc:move_to(self.object:position(),VEC_ZERO)
			self.ptc:play(false)
		end
	end
	
	local status = (var.timer > 2000) and (var.delay - var.timer) > 500
	for idx=1,#self.flame do
		self.flame[idx]:Update(status)
	end
	
	self.snd.volume = math.min(var.timer / 2000,1)
	if (self.snd:playing() ~= true) then
		self.snd:play_at_pos(self.object,self.object:position(),0,(sound_object.s3d))
	end
	if (self.snd:playing() == true) then
		self.snd:set_position(self.object:position())
	end
end

function CFlameBinder:Release()
	if (self.ptc) then
		self.ptc:stop()
		self.ptc = nil
	end
	if (self.snd) then
		self.snd:stop()
		self.snd = nil
	end
	
	for idx=1,#self.flame do
		self.flame[idx]:Remove()
		self.flame[idx] = nil
	end
	
	MGR:FlameRemove(self.object:id())
	alife_release(alife_object(self.object:id()))
end

--[[----------------------------------------------------------------------------------------------------
	Schemes
------------------------------------------------------------------------------------------------------]]
function CFlameBinder:net_spawn(se_abstract)
	if not (object_binder.net_spawn(self,se_abstract)) then
		return false
	end
	db.add_obj(self.object)
	add_binded_object(self.object)
	return true
end

function CFlameBinder:net_destroy()
	db.del_obj(self.object)
	del_binded_object(self.object)
	object_binder.net_destroy(self)
end

function CFlameBinder:net_save_relevant()
	return true
end

function CFlameBinder:save(packet)
	object_binder.save(self,packet)
	set_save_marker(packet,"save",false,"physics_binder")
	xr_logic.save_obj(self.object,packet)
	set_save_marker(packet,"save",true,"physics_binder")
end

function CFlameBinder:load(packet)
	object_binder.load(self,packet)
	set_save_marker(packet,"load",false,"physics_binder")
	xr_logic.load_obj(self.object,packet)
	set_save_marker(packet,"load",true,"physics_binder")
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	MGR = CFlameManager()
end