--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

--[[----------------------------------------------------------------------------------------------------
	Utilities
------------------------------------------------------------------------------------------------------]]
function object_by_id(id)
	return id and (db.storage[id] and db.storage[id].object or level.object_by_id(id))
end

--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
_G.IED_MGR = nil

class "CIedManager"
function CIedManager:__init()
	self.IED_STORAGE = {}
	self.IED_INITIAL = {}
	
	self.cfg_item_to_blow = {}
	self.cfg_blow_to_item = {}
	
	local ini = ini_file([[items\settings\deploy.ltx]])
	if (ini:section_exist("ieds")) then
		for idx,val in pairs(utils_data.collect_section(ini,"ieds",true)) do
			if (ini_sys:section_exist(idx) and ini_sys:section_exist(val) and self:IsIed(val)) then
				self.cfg_item_to_blow[idx] = val
				self.cfg_blow_to_item[val] = idx
			else
				DEBUG("Wrong parameters [%s] = %s | [%s] %s",idx,val,ini_sys:section_exist(idx),ini_sys:section_exist(val))
			end
		end
	end
	
	RegisterScriptCallback("save_state",self)
	RegisterScriptCallback("load_state",self)
	RegisterScriptCallback("actor_on_first_update",self)
	RegisterScriptCallback("server_entity_on_unregister",self)
	RegisterScriptCallback("actor_on_item_before_pickup",self)
end

function CIedManager:save_state(m_data)
	m_data.GT_IED_STORAGE = self.IED_STORAGE
end

function CIedManager:load_state(m_data)
	self.IED_STORAGE = m_data.GT_IED_STORAGE or {}
end

function CIedManager:server_entity_on_unregister(se,flag)
	if (flag == "se_explosive") and (self:IsIed(se:section_name())) then
		DEBUG("server_entity_on_unregister(%s)",se:name())
		self.IED_STORAGE[se.id] = nil
	end
end

function CIedManager:IsIed(sec)
	return sec and (SYS_GetParam(0,sec,"kind") == "e_ied") and true or false
end

function CIedManager:ItemToBlow(sec)
	return sec and self.cfg_item_to_blow[sec]
end

function CIedManager:BlowToItem(sec)
	return sec and self.cfg_blow_to_item[sec]
end

function CIedManager:Storage()
	return self.IED_STORAGE
end

function CIedManager:StorageById(oid)
	return oid and self.IED_STORAGE[oid]
end

function CIedManager:Initial()
	return self.IED_INITIAL
end

function CIedManager:Create(prs,owner_actor)
	local sec = prs and prs.sec
	local pos = prs and prs.pos
	local vid = prs and prs.vid
	local gid = prs and prs.gid
	local ang = prs and prs.ang
	local fix = prs and prs.fix
	if (sec and pos and vid and gid and ang and self:IsIed(sec)) then
		local se = alife_create(sec,pos,vid,gid)
		se.angle = vector():set(ang.y,ang.x,ang.z)
		
		local mem = self:StorageById(se.id)
		if (fix) then
			mem.fix = fix
			mem.pos = {x = pos.x,y = pos.y,z = pos.z}
			mem.ang = {x = ang.x,y = ang.y,z = ang.z}
		else
			self.IED_INITIAL[se.id] = {pos = pos,ang = ang}
		end
		if (owner_actor) then
			mem.owner_actor = true
		end
		return true
	end
	DEBUG("Wrong parameters %s %s %s %s %s",sec,pos,vid,gid,ang)
	return false
end

function CIedManager:actor_on_item_before_pickup(obj,flags)
	if (self:BlowToItem(obj:section())) then
		CreateTimeEvent(AC_ID,"pickup_ied",0,self.PickupTimeEvent,self,obj:id())
		flags.ret_value = false
	end
end

function CIedManager:PickupTimeEvent(oid)
	local obj = object_by_id(self.pickup_id)
	local sec = obj and self:BlowToItem(obj:section())
	if (sec) then
		alife_create_item(sec,db.actor)
		alife_release(obj)
		news_manager.relocate_item(db.actor,"in",sec)
	end
	return true
end

function CIedManager:Explode(num)
	for id,k in pairs(self.IED_STORAGE) do
		if (k.num == num) then
			local obj = object_by_id(id)
			if (obj and obj:condition() > 0) then
				local h = hit()
				h.type		= hit.fire_wound
				h.power		= 100
				h.impulse	= 0.0
				h.direction = vector():set(0,1,0)
				h.draftsman = db.actor
				obj:hit(h)
				obj:set_condition(0)
			end
			break
		end
	end
end

--[[----------------------------------------------------------------------------------------------------
	Main
------------------------------------------------------------------------------------------------------]]
function remote_desc(obj)
	return GT("st_ied_remote")
end

function remote_func(obj)
	if (deploy_condition() and IED_MGR:ItemToBlow(obj:section())) then
		if (HUD) then
			HUD:Close()
		end
		hud_deploy_active(obj)
	end
end

function deploy_condition()
	if not (db.actor:alive()) then
		return false
	end
	if (db.actor:get_attached_vehicle()) then
		return false
	end
	if (db.actor:is_talking()) then
		return false
	end
	if (IsMoveState("mcClimb")) then
		return false
	end
	return true
end

--[[----------------------------------------------------------------------------------------------------
	HUD
------------------------------------------------------------------------------------------------------]]
HUD = nil

function hud_deploy_active(obj)
	if (HUD == nil) then
		HUD = UIDeploy(obj)
		get_hud():AddDialogToRender(HUD)
		RegisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_remove()
	if (HUD) then
		get_hud():RemoveDialogToRender(HUD)
		HUD = nil
		UnregisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_update()
	if (HUD) then
		HUD:Update(true)
	end
end

function on_key_press(dik)
	if (HUD) then
		HUD:OnKeyPress(dik)
	end
end

class "UIDeploy" (CUIScriptWnd)
function UIDeploy:__init(obj) super(obj)
	self:SetWndRect(Frect():set(0,0,1280,768))
	self:SetAutoDelete(true)
	
	self.oid = obj:id()
	self.sec = obj:section()
	self.vis = self:GetAttachmentVisual(obj)
	self.atm_name = "deploy_ied"
	self.dist_def = 1
	self.dist_max = 3
	
	self.radius_min = 0.0
	self.radius_max = 1.0
	self.height_min = -1.8
	self.height_max = 0.5
	
	self.active = db.actor:active_slot()
	self.hiding = (self.active ~= 0) and true or false
	db.actor:activate_slot(0)
	hide_hud_inventory()
end

function UIDeploy:__finalize()
end

function UIDeploy:Update()
	CUIScriptWnd.Update(self)
	
	if not (main_hud_shown()) then
		return self:Close()
	end
	
	if not (deploy_condition()) then
		return self:Close()
	end
	
	if not (object_by_id(self.oid)) then
		return self:Close()
	end
	
	if not (self.vis) then
		return self:Close()
	end
	
	if (self.hiding) then
		if (db.actor:active_slot() == 0) then
			self.hiding = false
		elseif (db.actor:active_slot() ~= self.active) then
			return self:Close()
		end
	else
		if (db.actor:active_slot() ~= 0) then
			return self:Close()
		end
	end
	
	self.pos = self:GetDeployPosition()
	self.dir = self:GetDeployRotation()
	
	if (self.pos) then
		if (level.get_attachment(self.atm_name) == nil) then
			level.add_attachment(self.atm_name,self.vis)
		end
		local atm = level.get_attachment(self.atm_name)
		if (atm) then
			atm:set_position(self.pos)
			if (self.dir) then
				local h = math.deg(self.dir:getH())
				local p = math.deg(self.dir:getP()) + 90
				local a = vector():invert(self.dir):dotproduct(VEC_Y)
				if (math.acos(math.abs(clamp(a,-1,1))) < math.rad(1)) then
					h = math.deg(device().cam_dir:getH())
					p = (a > 0) and 0 or 180
				end
				atm:set_rotation(h,p,0)
			else
				local h = math.deg(device().cam_dir:getH())
				atm:set_rotation(h,0,0)
			end
		end
	end
end

function UIDeploy:Deploy()
	if (self.hiding) then
		return
	end
	local atm = level.get_attachment(self.atm_name)
	local xfm = atm and atm:get_transform()
	if not (xfm) then
		return
	end
	local obj = object_by_id(self.oid)
	local k = {}
	k.sec = IED_MGR:ItemToBlow(obj:section())
	k.pos = vector():set(xfm.c)
	k.vid = db.actor:level_vertex_id()
	k.gid = db.actor:game_vertex_id()
	k.ang = xfm:getHPB()
	k.fix = self.dir and true or false
	if (IED_MGR:Create(k,true)) then
		itms_manager.play_item_sound(obj,0.75)
		news_manager.relocate_item(db.actor,"out",obj:section())
		alife_release(obj)
	end
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:GetAttachmentVisual(obj)
	local sec = obj and IED_MGR:ItemToBlow(obj:section())
	return sec and SYS_GetParam(0,sec,"visual")
end

function UIDeploy:GetDeployPosition()
	local pos = device().cam_pos
	local dir = device().cam_dir
	local ray = ray_pick(pos,dir,self.dist_max,2,db.actor)
	local vec = ray:query() and vector():mad(pos,dir,ray:get_distance())
	if (self:ValidatePosition(vec)) then
		self.can_deploy_on_surface = true
		return vec
	end
	self.can_deploy_on_surface = false
	return vector():mad(pos,dir,self.dist_def)
end

function UIDeploy:GetDeployRotation()
	if not (self.can_deploy_on_surface) then
		return
	end
	local pos = device().cam_pos
	local dir = device().cam_dir
	local xfm = matrix():setHPB(dir:getH(),dir:getP(),0):translate_over(pos)
	
	local k = {}
	k[1] = vector():set(1,0,0):mul(-0.04)
	k[2] = vector():set(1,0,0):mul(0.04)
	k[3] = vector():set(0,1,0):mul(-0.04)
	k[4] = vector():set(0,1,0):mul(0.04)
	local t = {}
	for i=1,4 do
		local tmp = vector()
		xfm:transform_tiny(tmp,k[i])
		local ray = ray_pick(tmp,dir,self.dist_max,2,db.actor)
		local num = ray:query() and ray:get_distance() or self.dist_max
		t[i] = vector():mad(tmp,dir,num)
	end
	if (t[1] and t[2] and t[3] and t[4]) then
		local horz = vector():sub(t[2],t[1])
		local vert = vector():sub(t[4],t[3])
		return vector_cross(horz,vert):normalize()
	end
end

function UIDeploy:ValidatePosition(vec)
	if not (vec) then
		return false
	end
	local rds = device().cam_pos:distance_to_xz_sqr(vec)
	if (rds < math.pow(self.radius_min,2)) or (rds > math.pow(self.radius_max,2)) then
		return false
	end
	local tmp = vec.y - device().cam_pos.y
	if (tmp < self.height_min) or (tmp > self.height_max) then
		return false
	end
	return true
end

function UIDeploy:ResumeActive()
	if (self.active ~= 0) then
		db.actor:activate_slot(self.active)
	end
end

function UIDeploy:Cancel()
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:Close()
	if (level.get_attachment(self.atm_name)) then
		level.remove_attachment(self.atm_name)
	end
	hud_deploy_remove()
end

function UIDeploy:OnKeyPress(dik)
	if (dik == DIK_keys.MOUSE_1) then
		return self:Deploy()
	end
	if (dik == DIK_keys.MOUSE_2) then
		return self:Cancel()
	end
end

--[[----------------------------------------------------------------------------------------------------
	Binder
------------------------------------------------------------------------------------------------------]]
function init(obj)
	obj:bind_object(CExplosiveBinder(obj))
end

class "CExplosiveBinder" (object_binder)
function CExplosiveBinder:__init(obj) super(obj)
	db.storage[self.object:id()] = {}
	self.oid = self.object:id()
	self.mem = IED_MGR:StorageById(self.oid)
end

function CExplosiveBinder:update(delta)
	object_binder.update(self,delta)
end

function CExplosiveBinder:InitPosition()
	local tmp = IED_MGR:Initial()[self.oid]
	if (tmp) then
		if (tmp.pos) then
			self.object:force_set_position(tmp.pos)
		end
		if (tmp.ang) then
			self.object:force_set_rotation(tmp.ang)
		end
		IED_MGR:Initial()[self.oid] = nil
	end
end

function CExplosiveBinder:AfterNetSpawnTimeEvent(oid)
	local obj = object_by_id(oid)
	local mgr = obj and obj:binded_object()
	if (mgr) then
		mgr:AfterNetSpawn()
	end
	return true
end

function CExplosiveBinder:AfterNetSpawn()
	-- This binder net_spawn runs before object net_spawn so objects still haven't had physic shell yet.
	if (self.mem and self.mem.fix) then
		-- Physic shell should be available now but still check just in case.
		if (self.object:get_physics_shell()) then
			local ele = self.object:get_physics_shell():get_element_by_order(0)
			if (ele:is_fixed() == false) then
				ele:fix()
			end
		end
		local pos = self:GetStoragePosition()
		if (pos) then
			self.object:force_set_position(pos)
		end
		local ang = self:GetStorageRotation()
		if (ang) then
			self.object:force_set_rotation(ang)
		end
	end
end

function CExplosiveBinder:GetStoragePosition()
	if (self.mem and self.mem.pos) then
		local x = tonumber(self.mem.pos.x)
		local y = tonumber(self.mem.pos.y)
		local z = tonumber(self.mem.pos.z)
		return x and y and z and vector():set(x,y,z)
	end
end

function CExplosiveBinder:GetStorageRotation()
	if (self.mem and self.mem.ang) then
		local x = tonumber(self.mem.ang.x)
		local y = tonumber(self.mem.ang.y)
		local z = tonumber(self.mem.ang.z)
		return x and y and z and vector():set(x,y,z)
	end
end

----------------------------------------------------------------------------------------------------
function CExplosiveBinder:reload(section)
	object_binder.reload(self,section)
end

function CExplosiveBinder:reinit()
	object_binder.reinit(self)
	db.storage[self.object:id()] = db.storage[self.object:id()] or {}
	self.st = db.storage[self.object:id()]
end

function CExplosiveBinder:net_spawn(se_abstract)
	if not (object_binder.net_spawn(self,se_abstract)) then
		return false
	end
	db.add_obj(self.object)
	self:InitPosition()
	CreateTimeEvent(self.oid,"fix_bone_root",0,self.AfterNetSpawnTimeEvent,self,self.oid)
	return true
end

function CExplosiveBinder:net_destroy()
	db.del_obj(self.object)
	object_binder.net_destroy(self)
end

function CExplosiveBinder:net_save_relevant()
	return true
end

function CExplosiveBinder:save(packet)
	object_binder.save(self,packet)
	set_save_marker(packet,"save",false,"physics_binder")
	set_save_marker(packet,"save",true,"physics_binder")
end

function CExplosiveBinder:load(packet)
	object_binder.load(self,packet)
	set_save_marker(packet,"load",false,"physics_binder")
	set_save_marker(packet,"load",true,"physics_binder")
end

--[[----------------------------------------------------------------------------------------------------
	Callbacks
------------------------------------------------------------------------------------------------------]]
function on_show_hide()
	hud_deploy_update()
end

function actor_on_net_destroy()
	hud_deploy_remove()
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	_G.IED_MGR = CIedManager()
	RegisterScriptCallback("GUI_on_show",on_show_hide)
	RegisterScriptCallback("GUI_on_hide",on_show_hide)
	RegisterScriptCallback("actor_on_net_destroy",actor_on_net_destroy)
end

function DEBUG(str,...)
	local func = debug.getinfo(2,"S").source
	local line = debug.getinfo(2,"l").currentline
	func = string.sub(func,#func - string.find(string.reverse(func),"\\") + 2,#func)
	local p = {...}
	if (p and (#p ~= 0)) then
		printf(string.format("[GhenTuong] %s:%s | %s",tostring(func),tostring(line),str),...)
	else
		printf(string.format("[GhenTuong] %s:%s | ",tostring(func),tostring(line)) .. "%s",str)
	end
end
