--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

local IED_MAP_SPOT_PICK = "ied_map_spot_pick"
local IED_MAP_SPOT_NONE = "ied_map_spot_none"

KEY_DETONATE_DEF = DIK_keys.DIK_J
KEY_DETONATE = KEY_DETONATE_DEF

local VEC_Y = vector():set(0,1,0)

db.ied_objects = {}

function add_ied(obj)
	db.ied_objects[obj:id()] = obj
end

function del_ied(obj)
	db.ied_objects[obj:id()] = nil
end

--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
_G.IED_MGR = nil

class "CIedManager"
function CIedManager:__init()
	self.IED_STORAGE = {}
	self.IED_INITIAL = {}
	
	self.cfg_item_to_object = {}
	self.cfg_object_to_item = {}
	
	local ini = ini_file([[items\settings\deploy.ltx]])
	if (ini:section_exist("ieds")) then
		for idx,val in pairs(utils_data.collect_section(ini,"ieds",true)) do
			if (ini_sys:section_exist(idx) and ini_sys:section_exist(val) and self:IsIed(val)) then
				self.cfg_item_to_object[idx] = val
				self.cfg_object_to_item[val] = idx
			else
				URB_TAC:DEBUG("Wrong parameters [%s] = %s | [%s] %s",idx,val,ini_sys:section_exist(idx),ini_sys:section_exist(val))
			end
		end
	end
	
	RegisterScriptCallback("save_state",self)
	RegisterScriptCallback("load_state",self)
	RegisterScriptCallback("server_entity_on_register",self)
	RegisterScriptCallback("server_entity_on_unregister",self)
	RegisterScriptCallback("map_spot_menu_add_property",self)
	RegisterScriptCallback("map_spot_menu_property_clicked",self)
	RegisterScriptCallback("actor_on_item_before_pickup",self)
	
	RegisterScriptCallback("GUI_on_show",self)
	RegisterScriptCallback("GUI_on_hide",self)
	RegisterScriptCallback("actor_on_net_destroy",self)
	RegisterScriptCallback("on_key_press",self)
end

function CIedManager:save_state(m_data)
	m_data.GT_IED_STORAGE = self.IED_STORAGE
end

function CIedManager:load_state(m_data)
	self.IED_STORAGE = m_data.GT_IED_STORAGE or {}
end

function CIedManager:server_entity_on_register(se,flag)
	if (flag == "se_explosive") and (self:IsIed(se:section_name())) then
		if (self.IED_STORAGE[se.id] == nil) then
			self.IED_STORAGE[se.id] = {}
		end
		URB_TAC:DEBUG("server_entity_on_register(%s)",se:name())
	end
end

function CIedManager:server_entity_on_unregister(se,flag)
	if (flag == "se_explosive") and (self:IsIed(se:section_name())) then
		URB_TAC:DEBUG("server_entity_on_unregister(%s)",se:name())
		self.IED_STORAGE[se.id] = nil
	end
end

function CIedManager:IsIed(sec)
	return sec and (SYS_GetParam(0,sec,"kind") == "e_ied") and true or false
end

function CIedManager:ItemToObject(sec)
	return sec and self.cfg_item_to_object[sec]
end

function CIedManager:ObjectToItem(sec)
	return sec and self.cfg_object_to_item[sec]
end

function CIedManager:Storage()
	return self.IED_STORAGE
end

function CIedManager:StorageById(oid)
	return oid and self.IED_STORAGE[oid]
end

function CIedManager:Initial()
	return self.IED_INITIAL
end

function CIedManager:Create(prs,owner_actor)
	local sec = prs and prs.sec
	local pos = prs and prs.pos
	local vid = prs and prs.vid
	local gid = prs and prs.gid
	local ang = prs and prs.ang
	local fix = prs and prs.fix
	if (sec and pos and vid and gid and ang and self:IsIed(sec)) then
		local se = alife_create(sec,pos,vid,gid)
		se.angle = vector():set(ang.y,ang.x,ang.z)
		
		local mem = IED_MGR:StorageById(se.id)
		if (fix) then
			mem.fix = fix
			mem.pos = {x = pos.x,y = pos.y,z = pos.z}
			mem.ang = {x = ang.x,y = ang.y,z = ang.z}
		else
			self.IED_INITIAL[se.id] = {pos = pos,ang = ang}
		end
		if (owner_actor) then
			mem.owner_actor = true
		end
		return true
	end
	URB_TAC:DEBUG("Wrong parameters %s %s %s %s %s",sec,pos,vid,gid,ang)
	return false
end

function CIedManager:map_spot_menu_add_property(property_ui,oid,lvl)
	local obj = db.ied_objects[oid]
	if (obj) then
		local mem = IED_MGR:StorageById(oid)
		if (mem and mem.owner_actor) then
			if (mem.is_selected) then
				property_ui:AddItem(GT("ied_remote_spot_none"))
			else
				property_ui:AddItem(GT("ied_remote_spot_pick"))
			end
		end
	end
end

function CIedManager:map_spot_menu_property_clicked(property_ui,oid,lvl,sec)
	local obj = db.ied_objects[oid]
	if (obj) then
		local mem = IED_MGR:StorageById(oid)
		if (mem and mem.owner_actor) then
			if (sec == GT("ied_remote_spot_none")) then
				mem.is_selected = nil
				obj:binded_object():UpdateMapSpot(true)
			end
			if (sec == GT("ied_remote_spot_pick")) then
				mem.is_selected = true
				obj:binded_object():UpdateMapSpot(true)
			end
		end
	end
end

function CIedManager:actor_on_item_before_pickup(obj,flags)
	if (self:ObjectToItem(obj:section())) then
		CreateTimeEvent(AC_ID,"pickup",0,self.PickupTimeEvent,self,obj:id())
		flags.ret_value = false
	end
end

function CIedManager:PickupTimeEvent(oid)
	local obj = db.ied_objects[oid]
	local sec = obj and self:ObjectToItem(obj:section())
	if (sec) then
		alife_create_item(sec,db.actor)
		alife_release(obj)
		news_manager.relocate_item(db.actor,"in",sec)
	end
	return true
end

function CIedManager:on_key_press(dik)
	if (dik == KEY_DETONATE) then
		if (db.actor:active_slot() == 8 and db.actor:active_item()) then
			self:Explode()
		end
	end
end

function CIedManager:Explode()
	for oid,obj in pairs(db.ied_objects) do
		if (obj:condition() > 0 and IED_MGR:StorageById(oid).owner_actor) then
			local h = hit()
			h.type		= hit.fire_wound
			h.power		= 100
			h.impulse	= 0.0
			h.direction = vector():set(0,1,0)
			h.draftsman = db.actor
			obj:hit(h)
			obj:set_condition(0)
		end
	end
end

function CIedManager:GUI_on_show()
	hud_deploy_update()
end

function CIedManager:GUI_on_hide()
	hud_deploy_update()
end

function CIedManager:actor_on_net_destroy()
	hud_deploy_remove()
end


--[[----------------------------------------------------------------------------------------------------
	Main
------------------------------------------------------------------------------------------------------]]
function deploy_desc(obj)
	return GT("ied_remote_deploy")
end

function deploy_func(obj)
	if (deploy_condition() and IED_MGR:ItemToObject(obj:section())) then
		if (HUD) then
			HUD:Close()
		end
		hud_deploy_active(obj)
	end
end

function deploy_condition()
	if not (db.actor:alive()) then
		return false
	end
	if (db.actor:get_attached_vehicle()) then
		return false
	end
	if (db.actor:is_talking()) then
		return false
	end
	if (IsMoveState("mcClimb")) then
		return false
	end
	return true
end

--[[----------------------------------------------------------------------------------------------------
	HUD
------------------------------------------------------------------------------------------------------]]
HUD = nil

function hud_deploy_active(obj)
	if (HUD == nil) then
		HUD = UIDeploy(obj)
		get_hud():AddDialogToRender(HUD)
		RegisterScriptCallback("on_key_press",hud_on_key_press)
	end
end

function hud_deploy_remove()
	if (HUD) then
		get_hud():RemoveDialogToRender(HUD)
		HUD = nil
		UnregisterScriptCallback("on_key_press",hud_on_key_press)
	end
end

function hud_deploy_update()
	if (HUD) then
		HUD:Update(true)
	end
end

function hud_on_key_press(dik)
	if (HUD) then
		HUD:OnKeyPress(dik)
	end
end

class "UIDeploy" (CUIScriptWnd)
function UIDeploy:__init(obj) super(obj)
	self:SetWndRect(Frect():set(0,0,1280,768))
	self:SetAutoDelete(true)
	
	self.oid = obj:id()
	self.sec = obj:section()
	self.vis = self:GetAttachmentVisual(obj)
	self.atm_name = "deploy_ied"
	self.fix = false
	
	self.dist_def = 1.0
	self.dist_max = 1.5
	
	self.active = db.actor:active_slot()
	self.hiding = (self.active ~= 0) and true or false
	db.actor:activate_slot(0)
	hide_hud_inventory()
end

function UIDeploy:__finalize()
end

function UIDeploy:Update()
	CUIScriptWnd.Update(self)
	
	if not (main_hud_shown()) then
		return self:Close()
	end
	
	if not (deploy_condition()) then
		return self:Close()
	end
	
	if not (URB_TAC:object_by_id(self.oid)) then
		return self:Close()
	end
	
	if not (self.vis) then
		return self:Close()
	end
	
	if (self.hiding) then
		if (db.actor:active_slot() == 0) then
			self.hiding = false
		elseif (db.actor:active_slot() ~= self.active) then
			return self:Close()
		end
	else
		if (db.actor:active_slot() ~= 0) then
			return self:Close()
		end
	end
	
	local xfm = self:AttachmentTransform()
	if (xfm) then
		if (level.get_attachment(self.atm_name) == nil) then
			level.add_attachment(self.atm_name,self.vis)
		end
		local atm = level.get_attachment(self.atm_name)
		if (atm) then
			atm:set_position(xfm.c)
			local hpb = xfm:getHPB()
			atm:set_rotation(math.deg(hpb.x),math.deg(hpb.y),math.deg(hpb.z))
		end
	end
end

function UIDeploy:AttachmentTransform()
	local pos = device().cam_pos
	local dir = device().cam_dir
	local ray = ray_pick(pos,dir,self.dist_max,2,db.actor)
	if (ray:query()) then
		self.fix = true
		local vec = vector():mad(pos,dir,ray:get_distance())
		local nor = ray:get_normal()
		local h = dir:getH()
		local p = 0
		local b = 0
		if (math.abs(math.acos(nor:dotproduct(VEC_Y))) > math.rad(1)) then
			p = nor:getP() + (math.pi / 2)
			b = nor:getH() - dir:getH() + math.pi
		end
		return matrix():setHPB(h,p,b):translate_over(vec)
	end
	self.fix = false
	return matrix():setHPB(dir:getH(),0,0):translate_over(vector():mad(pos,dir,self.dist_def))
end

function UIDeploy:Deploy()
	if (self.hiding) then
		return
	end
	local atm = level.get_attachment(self.atm_name)
	local xfm = atm and atm:get_transform()
	if not (xfm) then
		return
	end
	local obj = URB_TAC:object_by_id(self.oid)
	local k = {}
	k.sec = IED_MGR:ItemToObject(obj:section())
	k.pos = vector():set(xfm.c)
	k.vid = db.actor:level_vertex_id()
	k.gid = db.actor:game_vertex_id()
	k.ang = xfm:getHPB()
	k.fix = self.fix
	if (IED_MGR:Create(k,true)) then
		itms_manager.play_item_sound(obj,0.75)
		news_manager.relocate_item(db.actor,"out",obj:section())
		alife_release(obj)
	end
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:GetAttachmentVisual(obj)
	local sec = obj and IED_MGR:ItemToObject(obj:section())
	return sec and SYS_GetParam(0,sec,"visual")
end

function UIDeploy:ResumeActive()
	if (self.active ~= 0) then
		db.actor:activate_slot(self.active)
	end
end

function UIDeploy:Cancel()
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:Close()
	level.remove_attachment(self.atm_name)
	hud_deploy_remove()
end

function UIDeploy:OnKeyPress(dik)
	if (dik == DIK_keys.MOUSE_1) then
		return self:Deploy()
	end
	if (dik == DIK_keys.MOUSE_2) then
		return self:Cancel()
	end
end

--[[----------------------------------------------------------------------------------------------------
	Binder
------------------------------------------------------------------------------------------------------]]
function init(obj)
	obj:bind_object(CIedBinder(obj))
end

class "CIedBinder" (object_binder)
function CIedBinder:__init(obj) super(obj)
	db.storage[self.object:id()] = {}
	self.oid = self.object:id()
	self.mem = IED_MGR:StorageById(self.oid)
end

function CIedBinder:update(delta)
	object_binder.update(self,delta)
end

function CIedBinder:InitPosition()
	local tmp = IED_MGR:Initial()[self.oid]
	if (tmp) then
		if (tmp.pos) then
			self.object:force_set_position(tmp.pos)
		end
		if (tmp.ang) then
			self.object:force_set_rotation(tmp.ang)
		end
		IED_MGR:Initial()[self.oid] = nil
	end
end

function CIedBinder:AfterNetSpawnTimeEvent(oid)
	local obj = URB_TAC:object_by_id(oid)
	local mgr = obj and obj:binded_object()
	if (mgr) then
		mgr:AfterNetSpawn()
	end
	return true
end

function CIedBinder:AfterNetSpawn()
	-- This binder net_spawn runs before object net_spawn so objects still haven't had physic shell yet.
	if (self.mem and self.mem.fix) then
		-- Physic shell should be available now but still check just in case.
		if (self.object:get_physics_shell()) then
			local ele = self.object:get_physics_shell():get_element_by_order(0)
			if (ele:is_fixed() == false) then
				ele:fix()
			end
		end
		local pos = self:GetStoragePosition()
		if (pos) then
			self.object:force_set_position(pos)
		end
		local ang = self:GetStorageRotation()
		if (ang) then
			self.object:force_set_rotation(ang)
		end
	end
end

function CIedBinder:GetStoragePosition()
	if (self.mem and self.mem.pos) then
		local x = tonumber(self.mem.pos.x)
		local y = tonumber(self.mem.pos.y)
		local z = tonumber(self.mem.pos.z)
		return x and y and z and vector():set(x,y,z)
	end
end

function CIedBinder:GetStorageRotation()
	if (self.mem and self.mem.ang) then
		local x = tonumber(self.mem.ang.x)
		local y = tonumber(self.mem.ang.y)
		local z = tonumber(self.mem.ang.z)
		return x and y and z and vector():set(x,y,z)
	end
end

function CIedBinder:UpdateMapSpot(enable)
	level.map_remove_all_object_spots(self.oid)
	if not (enable) then
		return
	end
	
	if not (self.object:condition() > 0 and self.mem.owner_actor) then
		return
	end
	
	if (self.mem.is_selected) then
		if (level.map_has_object_spot(self.oid,IED_MAP_SPOT_PICK) == 0) then
			local txt = ui_item.get_sec_short_name(self.object:section())
			txt = txt .. [[\n]] .. GT("ied_remote_spot_info")
			level.map_add_object_spot(self.oid,IED_MAP_SPOT_PICK,txt)
		end
	else
		if (level.map_has_object_spot(self.oid,IED_MAP_SPOT_NONE) == 0) then
			local txt = ui_item.get_sec_short_name(self.object:section())
			level.map_add_object_spot(self.oid,IED_MAP_SPOT_NONE,txt)
		end
	end
end

----------------------------------------------------------------------------------------------------
function CIedBinder:reload(section)
	object_binder.reload(self,section)
end

function CIedBinder:reinit()
	object_binder.reinit(self)
	db.storage[self.object:id()] = db.storage[self.object:id()] or {}
	self.st = db.storage[self.object:id()]
end

function CIedBinder:net_spawn(se_abstract)
	if not (object_binder.net_spawn(self,se_abstract)) then
		return false
	end
	db.add_obj(self.object)
	add_ied(self.object)
	self:InitPosition()
	self:UpdateMapSpot(true)
	CreateTimeEvent(self.oid,"after_net_spawn",0,self.AfterNetSpawnTimeEvent,self,self.oid)
	return true
end

function CIedBinder:net_destroy()
	self:UpdateMapSpot(false)
	
	db.del_obj(self.object)
	del_ied(self.object)
	object_binder.net_destroy(self)
end

function CIedBinder:net_save_relevant()
	return true
end

function CIedBinder:save(packet)
	object_binder.save(self,packet)
	set_save_marker(packet,"save",false,"physics_binder")
	set_save_marker(packet,"save",true,"physics_binder")
end

function CIedBinder:load(packet)
	object_binder.load(self,packet)
	set_save_marker(packet,"load",false,"physics_binder")
	set_save_marker(packet,"load",true,"physics_binder")
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	_G.IED_MGR = CIedManager()
end