--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
	To do:
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

MINE_IGNORE_ALLIES = MINE_IGNORE_ALLIES_DEF
MINE_IGNORE_ALLIES_DEF = true

local CHECKOUT_SND = [[weapons\generic_checkout]]

db.mine_objects = {}

function add_object(obj)
	db.mine_objects[obj:id()] = obj
end

function del_object(obj)
	db.mine_objects[obj:id()] = nil
end

--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
_G.MINE_MGR = nil

class "CMineManager"
function CMineManager:__init()
	self.MINE_MEM = {}
	
	self.cfg_item_to_object = {}
	self.cfg_object_to_item = {}
	
	do
		local ini = ini_file([[items\settings\deploy.ltx]])
		if (ini:section_exist("mines")) then
			for idx,val in pairs(utils_data.collect_section(ini,"mines",true)) do
				if (ini_sys:section_exist(idx) and ini_sys:section_exist(val)) then
					self.cfg_item_to_object[idx] = val
					self.cfg_object_to_item[val] = idx
				else
					URB_TAC:DEBUG("Wrong parameters [%s] %s",idx,val)
				end
			end
		end
	end
		
	RegisterScriptCallback("save_state",self)
	RegisterScriptCallback("load_state",self)
	RegisterScriptCallback("server_object_on_register",self)
	RegisterScriptCallback("server_object_on_unregister",self)
	RegisterScriptCallback("actor_on_first_update",self)
	RegisterScriptCallback("actor_on_item_use",self)
	RegisterScriptCallback("npc_on_before_hit",self)
	RegisterScriptCallback("anomaly_on_before_activate",self)
	
	RegisterScriptCallback("GUI_on_show",self)
	RegisterScriptCallback("GUI_on_hide",self)
	RegisterScriptCallback("actor_on_net_destroy",self)

end

function CMineManager:save_state(m_data)
	m_data.GT_MINE_MEM = self.MINE_MEM
end

function CMineManager:load_state(m_data)
	self.MINE_MEM = m_data.GT_MINE_MEM or {}
end

function CMineManager:actor_on_first_update()
	for oid,mem in pairs(self.MINE_MEM) do
		local se = alife_object(oid)
		if (mem.owner_actor and not simulation_objects.is_on_the_actor_level(se)) then
			DEBUG("Release mine for not in actor level [%s]",se:name())
			alife_release(se)
		end
	end
end

function CMineManager:server_object_on_register(se)
	if (self.cfg_object_to_item[se:section_name()]) then
		if (self.MINE_MEM[se.id] == nil) then
			self.MINE_MEM[se.id] = {}
			URB_TAC:DEBUG("MINE_MEM[%s] Storage create",se:name())
		end
	end
end

function CMineManager:server_object_on_unregister(se)
	if (self.cfg_object_to_item[se:section_name()]) then
		self.MINE_MEM[se.id] = nil
		URB_TAC:DEBUG("MINE_MEM[%s] Storage delete",se:name())
	end
end

function CMineManager:GUI_on_show()
	hud_deploy_update()
end

function CMineManager:GUI_on_hide()
	hud_deploy_update()
end

function CMineManager:actor_on_net_destroy()
	hud_deploy_remove()
end

function CMineManager:IsMine(sec)
	return sec and (SYS_GetParam(0,sec,"kind") == "e_mine") and true or false
end

function CMineManager:ItemToObject(sec)
	return sec and self.cfg_item_to_object[sec]
end

function CMineManager:ObjectToItem(sec)
	return sec and self.cfg_object_to_item[sec]
end

function CMineManager:StorageById(oid)
	return oid and self.MINE_MEM[oid]
end

function CMineManager:Create(prs,owner_actor)
	local sec = prs and prs.sec
	local pos = prs and prs.pos
	local vid = prs and prs.vid
	local gid = prs and prs.gid
	local ang = prs and prs.ang
	if (sec and pos and vid and gid and ang and self:IsMine(sec)) then
		local se = alife_create(sec,pos,vid,gid)
		se.angle = vector():set(ang.y,ang.x,ang.z)
		
		local mem = self:StorageById(se.id)
		mem.pos = {x = pos.x,y = pos.y,z = pos.z}
		mem.ang = {x = ang.x,y = ang.y,z = ang.z}
		
		self:SetOwnerActor(se.id)
		return true
	end
	URB_TAC:DEBUG("Wrong parameters %s %s %s %s %s",sec,pos,vid,gid,ang)
	return false
end

function CMineManager:GetOwnerActor(oid)
	local mem = self:StorageById(oid)
	return mem and mem.owner_actor and true or false
end

function CMineManager:SetOwnerActor(oid,status)
	local mem = self:StorageById(oid)
	if (mem) then
		if (status) then
			mem.owner_actor = true
		else
			mem.owner_actor = nil
		end
	end
end

function CMineManager:GetCommunity(oid)
	local mem = self:StorageById(oid)
	return mem and mem.community
end

function CMineManager:SetCommunity(oid,status)
	local mem = self:StorageById(oid)
	if (mem) then
		mem.community = status
	end
end

function CMineManager:actor_on_item_use(obj)
	if (self:ItemToObject(obj:section())) then
		if (HUD) then
			HUD:Close()
		end
		hud_deploy_active(obj)
	end
end

function CMineManager:npc_on_before_hit(npc,shit,bone_id,flags)
	if (db.mine_objects[shit.weapon_id] == nil) then
		return
	end
	if (db.mine_objects[shit.weapon_id]:binded_object():ValidateTarget(npc) == false) then
		flags.ret_value = false
	end
end

function CMineManager:anomaly_on_before_activate(ano,obj,flags)
	if (db.mine_objects[obj:id()]) then
		flags.ret_value = false
	end
end

--[[----------------------------------------------------------------------------------------------------
	Main
------------------------------------------------------------------------------------------------------]]
function deploy_condition()
	if not (db.actor:alive()) then
		return false
	end
	if (db.actor:get_attached_vehicle()) then
		return false
	end
	if (db.actor:is_talking()) then
		return false
	end
	if (IsMoveState("mcClimb")) then
		return false
	end
	return true
end

function pick_up_time_event(oid)
	local obj = db.mine_objects[oid]
	local sec = obj and MINE_MGR:ObjectToItem(obj:section())
	if (sec) then
		alife_create_item(sec,db.actor)
		alife_release(obj)
		news_manager.relocate_item(db.actor,"in",sec)
	end
	return true
end

--[[----------------------------------------------------------------------------------------------------
	UIDeploy
------------------------------------------------------------------------------------------------------]]
HUD = nil

function hud_deploy_active(obj)
	if (HUD == nil) then
		HUD = UIDeploy(obj)
		get_hud():AddDialogToRender(HUD)
		RegisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_remove()
	if (HUD) then
		get_hud():RemoveDialogToRender(HUD)
		HUD = nil
		UnregisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_update()
	if (HUD) then
		HUD:Update(true)
	end
end

function on_key_press(dik)
	if (HUD) then
		HUD:OnKeyPress(dik)
	end
end

class "UIDeploy" (CUIScriptWnd)
function UIDeploy:__init(obj) super(obj)
	self:SetAutoDelete(true)
	
	self.oid = obj:id()
	self.sec = obj:section()
	self.vis = self:GetAttachmentVisual(obj)
	self.atm_name = "deploy_mine"
	self.dist_def = 1
	self.dist_max = 3
	
	self.radius_min = 0.5
	self.radius_max = 1.0
	self.height_min = -1.8
	self.height_max = 0.0
	
	self.exclusive_radius = 0.4
	self.exclusive_height = 0.05
	self.vec_up = vector():set(VEC_Y)
	self.vec_dw = vector():set(self.vec_up):invert()
	
	self.rotation = 0
	
	self.active = db.actor:active_slot()
	self.hiding = (self.active ~= 0) and true or false
	
	if (self:FDDA() or self:FDDA_REDONE()) then
		self.active = nil
		self.hiding = false
		
		if (self:FDDA()) then
			zzz_ea_addon_backpack.active_slot = nil
			zzz_ea_addon_backpack.item_after_backpack = nil
		end
		
		if (self:FDDA_REDONE()) then
			lam2.cur_slot = nil
		end
	else
		self.active = db.actor:active_slot()
		self.hiding = (self.active ~= 0) and true or false
	end
	
	db.actor:activate_slot(0)
	hide_hud_inventory()
end

function UIDeploy:__finalize()
end

function UIDeploy:Update()
	CUIScriptWnd.Update(self)
	
	if not (main_hud_shown()) then
		return self:Close()
	end
	
	if not (deploy_condition()) then
		return self:Close()
	end
	
	if not (URB_TAC:object_by_id(self.oid)) then
		return self:Close()
	end
	
	if not (self.vis) then
		return self:Close()
	end
	
	if (self.hiding) then
		if (db.actor:active_slot() == 0) then
			self.hiding = false
		elseif (db.actor:active_slot() ~= self.active) then
			return self:Close()
		end
	else
		if (db.actor:active_slot() ~= 0) then
			return self:Close()
		end
	end
	
	self.pos = self:GetDeployPosition()
	self.dir = self:GetDeployRotation()
	
	if (self.pos and self.dir) then
		if (level.get_attachment(self.atm_name) == nil) then
			level.add_attachment(self.atm_name,self.vis)
		end
		local atm = level.get_attachment(self.atm_name)
		if (atm) then
			atm:set_position(self.pos)
			local h = math.deg(self.dir:getH())
			local p = math.deg(self.dir:getP())
			atm:set_rotation(h,p,0)
		end
	else
		if (level.get_attachment(self.atm_name)) then
			level.remove_attachment(self.atm_name)
		end
	end
end

function UIDeploy:FDDA()
	return zzz_ea_addon_backpack and true or false
end

function UIDeploy:FDDA_REDONE()
	return lam2 and true or false
end

function UIDeploy:Deploy()
	if (self.hiding) then
		return
	end
	local atm = level.get_attachment(self.atm_name)
	local xfm = atm and atm:get_transform()
	if not (xfm) then
		return
	end
	local obj = URB_TAC:object_by_id(self.oid)
	local k = {}
	k.sec = MINE_MGR:ItemToObject(obj:section())
	k.pos = vector():set(xfm.c)
	k.vid = db.actor:level_vertex_id()
	k.gid = db.actor:game_vertex_id()
	k.ang = xfm:getHPB()
	if (MINE_MGR:Create(k,true)) then
		itms_manager.play_item_sound(obj,0.75)
		news_manager.relocate_item(db.actor,"out",obj:section())
		alife_release(obj)
	end
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:Rotate(klockwise)
	local num = klockwise and -1 or 1
	self.rotation = clamp(self.rotation + num,-2,2)
end

function UIDeploy:GetAttachmentVisual(obj)
	local sec = obj and MINE_MGR:ItemToObject(obj:section())
	return sec and SYS_GetParam(0,sec,"visual")
end

function UIDeploy:GetDeployPosition()
	local pos = device().cam_pos
	local dir = vector():set(device().cam_dir.x,0,device().cam_dir.z):normalize()
	local ray = ray_pick(pos,dir,self.dist_def,2,db.actor)
	if (ray:query()) then
		return
	end
	local vec = vector():mad(pos,dir,self.dist_def)
	local tmp = pos.y - db.actor:position().y + 0.5
	local ray = ray_pick(vec,self.vec_dw,tmp,2,db.actor)
	if (ray:query()) then
		return vector():mad(vec,self.vec_dw,ray:get_distance())
	end
end

function UIDeploy:GetDeployRotation()
	if not (self.pos) then
		return
	end
	local src = vector():set(self.pos)
	local tmp = vector():set(src):add(vector():set(0,0.5,0))
	local dir = vector():setHP(device().cam_dir:getH() + math.rad(self.rotation * 45),0):normalize()
	local ray = ray_pick(tmp,dir,2,3,db.actor)
	if (ray:query()) then
		return
	end
	local vec = vector():mad(tmp,dir,2)
	local ray = ray_pick(vec,self.vec_dw,1,2,db.actor)
	if not (ray:query()) then
		return
	end
	local dst = vector():mad(vec,self.vec_dw,ray:get_distance())
	return vector():sub(dst,src):normalize()
end

function UIDeploy:ValidatePosition(vec)
	if not (vec) then
		return false
	end
	local rds = device().cam_pos:distance_to_xz_sqr(vec)
	if (rds < math.pow(self.radius_min,2)) or (rds > math.pow(self.radius_max,2)) then
		return false
	end
	local tmp = vec.y - device().cam_pos.y
	if (tmp < self.height_min) or (tmp > self.height_max) then
		return false
	end
	return true
end

function UIDeploy:ResumeActive()
	if (self.active and self.active ~= 0) then
		db.actor:activate_slot(self.active)
	end
end

function UIDeploy:Cancel()
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:Close()
	if (level.get_attachment(self.atm_name)) then
		level.remove_attachment(self.atm_name)
	end
	hud_deploy_remove()
end

function UIDeploy:OnKeyPress(dik)
	if (dik == DIK_keys.MOUSE_1) then
		return self:Deploy()
	end
	if (dik == DIK_keys.MOUSE_2) then
		return self:Cancel()
	end
	if (dik == bind_to_dik(key_bindings.kL_LOOKOUT)) then
		return self:Rotate(false)
	end
	if (dik == bind_to_dik(key_bindings.kR_LOOKOUT)) then
		return self:Rotate(true)
	end
end

--[[----------------------------------------------------------------------------------------------------
	Binder
------------------------------------------------------------------------------------------------------]]
function init(obj)
	obj:bind_object(CMineBinder(obj))
end

class "CMineBinder" (object_binder)
function CMineBinder:__init(obj) super(obj)
	db.storage[self.object:id()] = {}
	self.oid = self.object:id()
	self.psh = self.object:cast_PhysicsShellHolder()
	self.mem = MINE_MGR:StorageById(self.oid)
	
	self.destroy_time = SYS_GetParam(2,self.object:section(),"destroy_time") or 0
	
	self.defuse_use = SYS_GetParam(0,self.object:section(),"mine_defuse_use") == "true" and true or false
	self.defuse_tip = SYS_GetParam(0,self.object:section(),"mine_defuse_tip")
	
	do
		self.hide_bones = {}
		local str = SYS_GetParam(0,self.object:section(),"mine_hide_bones")
		if (str and str ~= "" and str ~= "nil") then
			for _,sec in ipairs(str_explode(str,",")) do
				local bid = self.object:bone_id(sec)
				assert(bid ~= 65535,strformat("[%s] Wrong parameters: %s %s",obj:section(),str,sec))
				self.hide_bones[bid] = true
			end
		end
	end
	
	self.fc_delta = nil
	self.fc_timer = nil
	self.fc_delay = 100
	self.object:set_fastcall(self.update,self)
end

function CMineBinder:reinit()
	object_binder.reinit(self)
	if (db.storage[self.object:id()] == nil) then
		db.storage[self.object:id()] = {}
	end
	self.st = db.storage[self.object:id()]
end

--[[----------------------------------------------------------------------------------------------------
	Update
------------------------------------------------------------------------------------------------------]]
function CMineBinder:update(delta)
	object_binder.update(self,delta)
	local t = time_global()
	if (self.fc_timer and (self.fc_timer > t)) then
		return
	end
	self.fc_delta = self.fc_timer and (t - self.fc_timer + self.fc_delay) or 0
	self.fc_timer = t + self.fc_delay
	
	if (self.mem.explode_timer and self.mem.explode_timer > 0) then
		self.mem.explode_timer = math.max(self.mem.explode_timer - self.fc_delta,0)
		if (self.mem.explode_timer == 0) then
			self:Explode()
		end
	end
end

function CMineBinder:OwnerActor()
	return self.mem.owner_actor and true or false
end

function CMineBinder:GetStoragePosition()
	if (self.mem and self.mem.pos) then
		local x = tonumber(self.mem.pos.x)
		local y = tonumber(self.mem.pos.y)
		local z = tonumber(self.mem.pos.z)
		return x and y and z and vector():set(x,y,z)
	end
end

function CMineBinder:GetStorageRotation()
	if (self.mem and self.mem.ang) then
		local x = tonumber(self.mem.ang.x)
		local y = tonumber(self.mem.ang.y)
		local z = tonumber(self.mem.ang.z)
		return x and y and z and vector():set(x,y,z)
	end
end

function CMineBinder:ValidateTarget(npc)
	if not (npc) then
		return false
	end
	
	if (npc:id() == AC_ID) then
		return true
	end
	
	if (IsStalker(npc)) then
		if (MINE_IGNORE_ALLIES and self:OwnerActor() and (npc:relation(db.actor) < game_object.enemy)) then
			return false
		end
	end
	return true
end

function CMineBinder:Trigger(who)
	if (self.mem.explode_timer == nil) then
		if (self.mem.current_parent_id == nil) then
			if (who and IsStalker(who)) then
				self.mem.current_parent_id = who:id()
			elseif (self:OwnerActor()) then
				self.mem.current_parent_id = AC_ID
			end
		end
		
		self.mem.explode_timer = self.destroy_time
		self.object:set_nonscript_usable(false)
		self.object:set_tip_text("")
		sound_object([[weapons\generic_checkout]]):play_no_feedback(self.object,sound_object.s3d,0,self.object:position(),1,1)
		self:HideBones()
	end
end

function CMineBinder:Explode()
	if (self.object:condition() > 0) then
		local who = URB_TAC:object_by_id(self.mem.current_parent_id)
		if (who and IsStalker(who)) then
			self.object:cast_Explosive():SetCurrentParentID(who:id())
		end
		self.object:cast_Explosive():Explode()
		self.object:set_condition(0)
	end
end

function CMineBinder:HideBones()
	if (self.hide_bones) then
		for bid,_ in pairs(self.hide_bones) do
			self.object:set_bone_visible(bid,false,false)
			self.psh:set_contact_collision_bone(bid,false,false)
		end
	end
end

function CMineBinder:hit_callback(obj,power,dir,who,bone_id)
	if (who and IsStalker(who)) then
		self:Trigger(who)
	end
end

function CMineBinder:contact_collision_callback(obj,obj_bid,who,who_bid)
	if (self:ValidateTarget(who)) then
		self:Trigger()
	end
	if (self.hide_bones[obj_bid]) then
		return false
	end
	return true
end

----------------------------------------------------------------------------------------------------
function CMineBinder:reload(section)
	object_binder.reload(self,section)
end

function CMineBinder:net_spawn(se_abstract)
	if not (object_binder.net_spawn(self,se_abstract)) then
		return false
	end
	db.add_obj(self.object)
	add_object(self.object)
	self.object:set_callback(callback.net_spawn_after,self.net_spawn_after,self)
	self.psh:set_script_contact_collision_callback(self.contact_collision_callback,self)
	
	return true
end

function CMineBinder:net_spawn_after()
	self.psh:activate_contact_collision_callback(true)
	
	if (self.object:get_physics_shell():get_element_by_order(0):is_fixed() == false) then
		self.object:get_physics_shell():get_element_by_order(0):fix()
	end
	
	local pos = self:GetStoragePosition()
	if (pos) then
		self.object:force_set_position(pos)
	end
	local ang = self:GetStorageRotation()
	if (ang) then
		self.object:force_set_rotation(ang)
	end
	
	if (self.mem.explode_timer == nil) then
		if (self.defuse_use) then
			self.object:set_nonscript_usable(true)
		end
		if (self.defuse_tip) then
			self.object:set_tip_text(self.defuse_tip)
		end
	else
		self:HideBones()
	end
end

function CMineBinder:net_destroy()
	self.object:set_callback(callback.hit,nil)
	self.object:set_callback(callback.net_spawn_after,nil)
	self.psh:set_script_contact_collision_callback(nil)
	db.del_obj(self.object)
	del_object(self.object)
	object_binder.net_destroy(self)
end

function CMineBinder:net_save_relevant()
	return true
end

function CMineBinder:save(packet)
	object_binder.save(self,packet)
	set_save_marker(packet,"save",false,"physics_binder")
	set_save_marker(packet,"save",true,"physics_binder")
end

function CMineBinder:load(packet)
	object_binder.load(self,packet)
	set_save_marker(packet,"load",false,"physics_binder")
	set_save_marker(packet,"load",true,"physics_binder")
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	_G.MINE_MGR = CMineManager()
end