--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
	To do:
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

_G.AddScriptCallback("drone_on_net")
_G.AddScriptCallback("drone_on_death")

local DRONE_MAP_SPOT = "drone_map_spot"

KEY_DETONATE_DEF = DIK_keys.DIK_J
KEY_DETONATE = KEY_DETONATE_DEF

HIDE_MINIMAP_DEF = true
HIDE_MINIMAP = HIDE_MINIMAP_DEF

db.drone_objects = {}

function add_object(obj)
	db.drone_objects[obj:id()] = obj
end

function del_object(obj)
	db.drone_objects[obj:id()] = nil
end

se_drones = {}

function _G.IsDrone(obj)
	local oid = obj and (type(obj.id) == "function" and obj:id() or obj.id)
	return oid and se_drones[oid] and true or false
end

--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
_G.DRONE_MGR = nil

class "CDroneManager"
function CDroneManager:__init()
	self.DRONE_STORAGE = {}
	
	self.cfg_item_to_object = {}
	self.cfg_object_to_item = {}
	
	do
		local ini = ini_file([[items\settings\deploy.ltx]])
		if (ini:section_exist("drones")) then
			for idx,val in pairs(utils_data.collect_section(ini,"drones",true)) do
				if (ini_sys:section_exist(idx) and ini_sys:section_exist(val) and self:IsDroneSection(val)) then
					self.cfg_item_to_object[idx] = val
					self.cfg_object_to_item[val] = idx
				else
					URB_TAC:DEBUG("Wrong parameters [%s] %s",idx,val)
				end
			end
		end
	end
	
	RegisterScriptCallback("save_state",self)
	RegisterScriptCallback("load_state",self)
	RegisterScriptCallback("server_entity_on_register",self)
	RegisterScriptCallback("server_entity_on_unregister",self)
	RegisterScriptCallback("actor_on_first_update",self)
	RegisterScriptCallback("map_spot_menu_add_property",self)
	RegisterScriptCallback("map_spot_menu_property_clicked",self)
	
	RegisterScriptCallback("actor_on_attach_vehicle",self)
	RegisterScriptCallback("actor_on_detach_vehicle",self)
	
	RegisterScriptCallback("GUI_on_show",self)
	RegisterScriptCallback("GUI_on_hide",self)
	RegisterScriptCallback("actor_on_net_destroy",self)
	RegisterScriptCallback("ActorMenu_on_item_drag_drop",self)
	
	RegisterScriptCallback("on_npc_vs_heli_eva",on_npc_vs_heli_eva)
	RegisterScriptCallback("on_npc_vs_heli_act",on_npc_vs_heli_act)
	
	if (rax_icon_layers) then
		rax_icon_layers.register("drone_icon_layer",drone_icon_layer)
	else
		rax_icon_layers_urban_tactics.register("drone_icon_layer",drone_icon_layer)
	end
	
	self.minimap_disabled = false
end

function CDroneManager:save_state(m_data)
	m_data.GT_DRONE_STORAGE = self.DRONE_STORAGE
end

function CDroneManager:load_state(m_data)
	self.DRONE_STORAGE = m_data.GT_DRONE_STORAGE or {}
end

function CDroneManager:actor_on_first_update()
--[[
	for idx=#self.DRONE_ACT_OWN,1,-1 do
		local id = self.DRONE_ACT_OWN[idx]
		local se = id and alife_object(id)
		if (se) then
			if not (simulation_objects.is_on_the_actor_level(se)) then
				if (self:IsDroneSection(se:section_name())) then
					URB_TAC:DEBUG("Release drone for not in actor level [%s]",se:name())
					alife_release(se)
				else
					URB_TAC:DEBUG("ERROR: object invalid [%s]",se:name())
					self:ActorOwnDel(se.id)
				end
			end
		else
			URB_TAC:DEBUG("ERROR: object does not exist")
			self:ActorOwnDel(se.id)
		end
	end
--]]
end

function CDroneManager:server_entity_on_register(se,flag)
	if (flag == "se_car") and (self:IsDroneSection(se:section_name())) then
		se_drones[se.id] = se
		if (self.DRONE_STORAGE[se.id] == nil) then
			self.DRONE_STORAGE[se.id] = {}
		end
		URB_TAC:DEBUG("server_entity_on_register(%s)",se:name())
	end
end

function CDroneManager:server_entity_on_unregister(se,flag)
	if (flag == "se_car") and (self:IsDroneSection(se:section_name())) then
		se_drones[se.id] = nil
		self.DRONE_STORAGE[se.id] = nil
		URB_TAC:DEBUG("server_entity_on_unregister(%s)",se:name())
	end
end

function CDroneManager:IsDroneSection(sec)
	return sec and (SYS_GetParam(0,sec,"kind") == "v_drone") and true or false
end

function CDroneManager:ItemToObject(sec)
	return sec and self.cfg_item_to_object[sec]
end

function CDroneManager:ObjectToItem(sec)
	return sec and self.cfg_object_to_item[sec]
end

function CDroneManager:StorageById(oid)
	return oid and self.DRONE_STORAGE[oid]
end

function CDroneManager:StorageCopy(src_id,dst_id)
	local sec = self:GetAttachSection(src_id)
	self:SetAttachSection(dst_id,sec)
end

function CDroneManager:Create(prs,owner_actor)
	local sec = prs and prs.sec
	local pos = prs and prs.pos
	local vid = prs and prs.vid
	local gid = prs and prs.gid
	local ang = prs and prs.ang
	local itm = prs and prs.itm
	if (sec and pos and vid and gid and ang and self:IsDroneSection(sec)) then
		local se = alife_create(sec,pos,vid,gid)
		se.angle = vector():set(ang.y,ang.x,ang.z)
		if (itm) then
			self:StorageCopy(itm:id(),se.id)
			self:StorageById(se.id).condition = itm:condition()
		end
		if (owner_actor) then
			self:StorageById(se.id).owner_actor = true
		end
		return true
	end
	URB_TAC:DEBUG("Wrong parameters %s %s %s %s %s",sec,pos,vid,gid,ang)
	return false
end

function CDroneManager:GetAttachSection(oid)
	return se_load_var(oid,nil,"drone_attach_section")
end

function CDroneManager:SetAttachSection(oid,sec)
	se_save_var(oid,nil,"drone_attach_section",sec)
end

function CDroneManager:DroneAttach(obj,itm)
	if not (self:ItemToObject(obj:section()) and IED_MGR:ItemToObject(itm:section())) then
		return
	end
	if (self:GetAttachSection(obj:id())) then
		return
	end
	self:SetAttachSection(obj:id(),itm:section())
	itms_manager.play_item_sound(itm,0.75)
	alife_release(itm)
end

function CDroneManager:DroneDetach(obj)
	if not (self:ItemToObject(obj:section())) then
		return
	end
	local sec = self:GetAttachSection(obj:id())
	if (sec) then
		alife_create_item(sec,db.actor)
		self:SetAttachSection(obj:id(),nil)
	end
end

function CDroneManager:SetServerItemCondition(itm,num)
	if (itm and num) then
		local pkt = utils_stpk.get_item_data(itm)
		pkt.condition = clamp(num,0,1)
		utils_stpk.set_item_data(pkt,itm)
		URB_TAC:DEBUG("[%s] num:%s",itm:name(),num)
	end
end

function CDroneManager:map_spot_menu_add_property(property_ui,oid,lvl)
	local obj = db.drone_objects[oid]
	if (obj) then
		property_ui:AddItem(GT("drone_pda_cmd_control"))
	end
end

function CDroneManager:map_spot_menu_property_clicked(property_ui,oid,lvl,sec)
	local obj = db.drone_objects[oid]
	if (obj) then
		if (sec == GT("drone_pda_cmd_control")) then
			if (obj:binded_object():CanTakeControl()) then
				db.actor:activate_slot(0)
				obj:binded_object():TakeControl()
			end
		end
	end
end

function CDroneManager:actor_on_attach_vehicle(obj)
	if (obj and IsDrone(obj)) then
		hud_camfpv_active()
		self:SetMinimap(false)
		RegisterScriptCallback("actor_on_update",self)
		RegisterScriptCallback("on_key_press",self)
	end
end

function CDroneManager:actor_on_detach_vehicle(obj)
	if (obj and IsDrone(obj)) then
		hud_camfpv_remove()
		self:SetMinimap(true)
		UnregisterScriptCallback("actor_on_update",self)
		UnregisterScriptCallback("on_key_press",self)
	end
end

function CDroneManager:actor_on_update()
	local obj = db.actor:get_attached_vehicle()
	if (obj and IsDrone(obj)) then
		if (obj:binded_object()) then
			obj:binded_object():ActorUpdate()
		end
	end
end

function CDroneManager:on_key_press(dik)
	if (dik == KEY_DETONATE) then
		local obj = db.actor:get_attached_vehicle()
		if (obj and IsDrone(obj)) then
			if (obj:binded_object()) then
				obj:binded_object():ExplosiveDetonate(db.actor)
			end
		end
	end
end

function CDroneManager:GUI_on_show()
	hud_deploy_update()
	hud_camfpv_update()
end

function CDroneManager:GUI_on_hide()
	hud_deploy_update()
	hud_camfpv_update()
end

function CDroneManager:actor_on_net_destroy()
	hud_deploy_remove()
	hud_camfpv_remove()
end

function CDroneManager:ActorMenu_on_item_drag_drop(itm,obj,slot_from,slot_next)
	if not (slot_from == EDDListType.iActorBag and slot_next == EDDListType.iActorBag) then
        return
    end
	if (self:ItemToObject(obj:section())) then
		self:DroneDetach(obj)
		self:DroneAttach(obj,itm)
	end
end

local drone_icon_scale = 0.5

function drone_icon_layer(cell,obj,sec)
	if not (cell.showcase == 0) then
		return
	end
	if not (DRONE_MGR:ItemToObject(sec)) then
		return
	end
	local tmp = DRONE_MGR:GetAttachSection(obj:id())
	if not (tmp) then
		return
	end
	
	local obj_axis = utils_xml.get_item_axis(sec)
	local itm_axis = utils_xml.get_item_axis(tmp)
	return {
		icon_layer = tmp,
		icon_layer_x = 0,
		icon_layer_y = obj_axis.h / drone_icon_scale - itm_axis.h,
		icon_layer_scale = drone_icon_scale,
	}
end

function CDroneManager:SetMinimap(state)
	if (ui_options.get([[video/hud/show_minimap]]) == false) then
		return
	end
	if (state) then
		ActorMenu.get_maingame().UIZoneMap.disabled = false
		ActorMenu.get_maingame().UIMotionIcon:Show(true)
	else
		ActorMenu.get_maingame().UIZoneMap.disabled = true
		ActorMenu.get_maingame().UIMotionIcon:Show(false)
	end
end

--[[----------------------------------------------------------------------------------------------------
	Item
------------------------------------------------------------------------------------------------------]]
function drone_deploy_desc(obj)
	return GT("drone_item_deploy")
end

function drone_deploy_func(obj)
	hud_deploy_active(obj)
end

function drone_detach_desc(obj)
	local sec = DRONE_MGR:GetAttachSection(obj:id())
	if (sec) then
		return strformat(GT("drone_item_detach"),ui_item.get_sec_short_name(sec))
	end
end

function drone_detach_func(obj)
	DRONE_MGR:DroneDetach(obj)
end

function deploy_condition()
	if not (db.actor:alive()) then
		return false
	end
	if (db.actor:get_attached_vehicle()) then
		return false
	end
	if (db.actor:is_talking()) then
		return false
	end
	if (IsMoveState("mcClimb")) then
		return false
	end
	return true
end

function on_before_hit(obj,shit,bone_id)
	return true
end

function on_before_use(obj,cam_pos,cam_dir,act_pos)
	CreateTimeEvent(obj:id(),"pickup",0,pick_up_time_event,obj:id())
	return false
end

function pick_up_time_event(oid)
	local obj = db.drone_objects[oid]
	local sec = obj and DRONE_MGR:ObjectToItem(obj:section())
	if (sec) then
		local mem = DRONE_MGR:StorageById(obj:id())
		local se = alife_create_item(sec,db.actor,{cond = clamp(mem.condition or 1,0,1)})
		DRONE_MGR:StorageCopy(obj:id(),se.id)
		alife_release(obj)
		news_manager.relocate_item(db.actor,"in",sec)
	end
	return true
end

function on_explode(obj)
	if (obj:binded_object()) then
		obj:binded_object():UpdateMapSpot(false)
	end
end

--[[----------------------------------------------------------------------------------------------------
	UIDeploy
------------------------------------------------------------------------------------------------------]]
HUD_DEPLOY = nil

function hud_deploy_active(obj)
	if (HUD_DEPLOY == nil) then
		HUD_DEPLOY = UIDeploy(obj)
		get_hud():AddDialogToRender(HUD_DEPLOY)
		RegisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_remove()
	if (HUD_DEPLOY) then
		get_hud():RemoveDialogToRender(HUD_DEPLOY)
		HUD_DEPLOY = nil
		UnregisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_update()
	if (HUD_DEPLOY) then
		HUD_DEPLOY:Update(true)
	end
end

function on_key_press(dik)
	if (HUD_DEPLOY) then
		HUD_DEPLOY:OnKeyPress(dik)
	end
end

class "UIDeploy" (CUIScriptWnd)
function UIDeploy:__init(obj) super(obj)
	self:SetAutoDelete(true)
	
	self.oid = obj:id()
	self.sec = obj:section()
	self.vis = self:GetAttachmentVisual(obj)
	self.atm_name = "deploy_drone"
	self.dist_def = 1
	self.dist_max = 3
	
	self.radius_min = 0.5
	self.radius_max = 1.0
	self.height_min = -1.8
	self.height_max = 0.0
	
	self.exclusive_radius = 0.4
	self.exclusive_height = 0.05
	self.vec_up = vector():set(VEC_Y)
	self.vec_dw = vector():set(self.vec_up):invert()
	
	if (self:FDDA() or self:FDDA_REDONE()) then
		self.active = nil
		self.hiding = false
		
		if (self:FDDA()) then
			zzz_ea_addon_backpack.active_slot = nil
			zzz_ea_addon_backpack.item_after_backpack = nil
		end
		
		if (self:FDDA_REDONE()) then
			lam2.cur_slot = nil
		end
	else
		self.active = db.actor:active_slot()
		self.hiding = (self.active ~= 0) and true or false
	end
	
	db.actor:activate_slot(0)
	hide_hud_inventory()
end

function UIDeploy:__finalize()
end

function UIDeploy:Update()
	CUIScriptWnd.Update(self)
	
	if not (main_hud_shown()) then
		return self:Close()
	end
	
	if not (deploy_condition()) then
		return self:Close()
	end
	
	if not (URB_TAC:object_by_id(self.oid)) then
		return self:Close()
	end
	
	if not (self.vis) then
		return self:Close()
	end
	
	if (self.hiding) then
		if (db.actor:active_slot() == 0) then
			self.hiding = false
		elseif (db.actor:active_slot() ~= self.active) then
			return self:Close()
		end
	else
		if (db.actor:active_slot() ~= 0) then
			return self:Close()
		end
	end
	
	self.pos = self:GetDeployPosition()
	
	if (self.pos) then
		if (level.get_attachment(self.atm_name) == nil) then
			level.add_attachment(self.atm_name,self.vis)
		end
		local atm = level.get_attachment(self.atm_name)
		if (atm) then
			atm:set_position(self.pos)
			local h = math.deg(device().cam_dir:getH())
			atm:set_rotation(h,0,0)
		end
	else
		if (level.get_attachment(self.atm_name)) then
			level.remove_attachment(self.atm_name)
		end
	end
end

function UIDeploy:FDDA()
	return zzz_ea_addon_backpack and true or false
end

function UIDeploy:FDDA_REDONE()
	return lam2 and true or false
end

function UIDeploy:Deploy()
	if (self.hiding) then
		return
	end
	local atm = level.get_attachment(self.atm_name)
	local xfm = atm and atm:get_transform()
	if not (xfm) then
		return
	end
	local obj = URB_TAC:object_by_id(self.oid)
	local k = {}
	k.sec = DRONE_MGR:ItemToObject(obj:section())
	k.pos = vector():set(xfm.c)
	k.vid = db.actor:level_vertex_id()
	k.gid = db.actor:game_vertex_id()
	k.ang = xfm:getHPB()
	k.itm = obj
	if (DRONE_MGR:Create(k,true)) then
		itms_manager.play_item_sound(obj,0.75)
		news_manager.relocate_item(db.actor,"out",obj:section())
		alife_release(obj)
	end
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:GetAttachmentVisual(obj)
	local sec = obj and DRONE_MGR:ItemToObject(obj:section())
	return sec and SYS_GetParam(0,sec,"visual")
end

function UIDeploy:GetDeployPosition()
	local pos = device().cam_pos
	local dir = vector():set(device().cam_dir.x,0,device().cam_dir.z):normalize()
	local ray = ray_pick(pos,dir,self.dist_def,2,db.actor)
	if (ray:query()) then
		return
	end
	local vec = vector():mad(pos,dir,self.dist_def)
	local tmp = pos.y - db.actor:position().y + 0.5
	local ray = ray_pick(vec,self.vec_dw,tmp,2,db.actor)
	if (ray:query()) then
		return vector():mad(vec,self.vec_dw,ray:get_distance())
	end
end

function UIDeploy:ResumeActive()
	if (self.active and self.active ~= 0) then
		db.actor:activate_slot(self.active)
	end
end

function UIDeploy:Cancel()
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:Close()
	if (level.get_attachment(self.atm_name)) then
		level.remove_attachment(self.atm_name)
	end
	hud_deploy_remove()
end

function UIDeploy:OnKeyPress(dik)
	if (dik == DIK_keys.MOUSE_1) then
		return self:Deploy()
	end
	if (dik == DIK_keys.MOUSE_2) then
		return self:Cancel()
	end
end

--[[----------------------------------------------------------------------------------------------------
	UICamfpv
------------------------------------------------------------------------------------------------------]]
HUD_CAMFPV = nil

function hud_camfpv_active()
	if (HUD_CAMFPV == nil) then
		HUD_CAMFPV = UICamfpv()
		get_hud():AddDialogToRender(HUD_CAMFPV)
	end
end

function hud_camfpv_remove()
	if (HUD_CAMFPV) then
		get_hud():RemoveDialogToRender(HUD_CAMFPV)
		HUD_CAMFPV = nil
	end
end

function hud_camfpv_update()
	if (HUD_CAMFPV) then
		HUD_CAMFPV:Update(true)
	end
end

class "UICamfpv" (CUIScriptWnd)
function UICamfpv:__init() super()
	self:SetAutoDelete(true)
	self.xml = CScriptXmlInit()
	self.xml:ParseFile("ui_drone_camfpv.xml")
	
	self.hud = self.xml:InitStatic("hud",self)
	self:ApplyScreenRatio(self.hud)
	
	self.info = self.xml:InitStatic("info",self)
	self:ApplyScreenRatio(self.info,false)
	self.info:SetTextureColor(GetARGB(128,0,0,0))
	
	self.dialog = self.xml:InitStatic("info:dialog",self.info)
	self:ApplyScreenRatio(self.dialog,true)
	
	self.sig_img = self.xml:InitStatic("info:dialog:signal_img",self.dialog)
	self.sig_bar = self.xml:InitProgressBar("info:dialog:signal_bar",self.dialog)
	self:ApplyScreenRatio(self.sig_img,true)
	self:ApplyScreenRatio(self.sig_bar,true)
	self:ApplyScreenRatio(self.sig_bar:GetProgressStatic(),true)
	self.sig_img:SetTextureColor(utils_xml.get_color("ui_gray_1",true))
	self.sig_max = math.floor(self.sig_bar:GetRange_max())
	
	self.btr_txt = self.xml:InitTextWnd("info:dialog:battery_txt",self.dialog)
	self.btr_img = self.xml:InitStatic("info:dialog:battery_img",self.dialog)
	self.btr_bar = self.xml:InitProgressBar("info:dialog:battery_bar",self.dialog)
	self:ApplyScreenRatio(self.btr_txt,true)
	self:ApplyScreenRatio(self.btr_img,true)
	self:ApplyScreenRatio(self.btr_bar,true)
	self:ApplyScreenRatio(self.btr_bar:GetProgressStatic(),true)
	
	self.CLR_G = utils_xml.get_color("d_green",true)
	self.CLR_Y = utils_xml.get_color("pda_yellow",true)
	self.CLR_R = utils_xml.get_color("d_red",true)
end

function UICamfpv:__finalize()
end

function UICamfpv:Update()
	CUIScriptWnd.Update(self)
	
	self.obj = db.actor:get_attached_vehicle()
	if not (self.obj and IsDrone(self.obj)) then
		return self:Close()
	end
	self.mem = DRONE_MGR:StorageById(self.obj:id())
	
	if not (main_hud_shown()) then
		self:Show(false)
		return
	end
	self:Show(true)
	
	self:UpdateInfo()
end

function UICamfpv:UpdateInfo()
	do
		local num = self:SignalPower()
		local clr = self:SignalColor(num)
		self.sig_bar:SetProgressPos(num)
		if (self.sig_clr ~= clr) then
			self.sig_clr = clr
			self.sig_bar:GetProgressStatic():SetTextureColor(self.sig_clr)
		end
		local bnk = (num <= 1) and true or false
		bnk = true
		self:ApplyBlink(self.sig_img,bnk)
		self:ApplyBlink(self.sig_bar:GetProgressStatic(),bnk)
	end
	do
		local num = clamp(self.mem and self.mem.condition or 1,0,1) * 100
		local clr = self:BatteryColor(num)
		self.btr_txt:SetText(strformat([[%s%]],math.floor(num)))
		self.btr_bar:SetProgressPos(num)
		self.btr_txt:SetTextColor(clr)
		self.btr_img:SetTextureColor(clr)
		self.btr_bar:SetColor(clr)
		
		local bnk = (num < 20) and true or false
		bnk = true
		self:ApplyBlink(self.btr_img,bnk)
		self:ApplyBlink(self.btr_bar:GetProgressStatic(),bnk)
	end
end

function UICamfpv:SignalPower()
	local sig = self.obj:binded_object().sig_radius
	local num = math.min(db.actor:position():distance_to(self.obj:position()),sig)
	return math.ceil(self.sig_max * (sig - num) / sig)
end

function UICamfpv:SignalColor(num)
	if (num <= 1) then
		return self.CLR_R
	end
	if (num <= 2) then
		return self.CLR_Y
	end
	return self.CLR_G
end

function UICamfpv:BatteryColor(num)
	if (num < 20) then
		return self.CLR_R
	end
	if (num < 50) then
		return self.CLR_Y
	end
	return self.CLR_G
end

function UICamfpv:ApplyBlink(ele,bnk)
	if (bnk) then
		if (ele:IsColorAnimationPresent() ~= true) then
			ele:SetColorAnimation("ui_medium_blinking_alpha",11,0)
		end
	else
		if (ele:IsColorAnimationPresent() == true) then
			ele:RemoveColorAnimation()
		end
	end
end

function UICamfpv:Close()
	self:Show(false)
	hud_camfpv_remove()
end

function UICamfpv:ScreenRatio()
	return (1024/768)/(device().width/device().height)
end

function UICamfpv:ApplyScreenRatio(ele,pos)
	ele:SetWndSize(vector2():set(ele:GetWidth()*self:ScreenRatio(),ele:GetHeight()))
	if (pos) then
		ele:SetWndPos(vector2():set(ele:GetWndPos().x*self:ScreenRatio(),ele:GetWndPos().y))
	end
end

--[[----------------------------------------------------------------------------------------------------
	Binder
------------------------------------------------------------------------------------------------------]]
function init(obj)
	obj:bind_object(CDroneBinder(obj))
end

class "CDroneBinder" (object_binder)
function CDroneBinder:__init(obj) super(obj)
	db.storage[self.object:id()] = {}
	self.oid = self.object:id()
	self.car = self.object:get_car()
	self.mem = DRONE_MGR:StorageById(self.oid)
	
	self.attach_bone = SYS_GetParam(0,self.object:section(),"attach_bone")
	
	self.power_cons = SYS_GetParam(2,self.object:section(),"power_cons") or 0
	self.power_crit = SYS_GetParam(2,self.object:section(),"power_crit") or 0
	self.sig_radius = SYS_GetParam(2,self.object:section(),"sig_radius") or 10000
	
	self.power_timer = 0
	self.power_delay = 1000
		
	self.fc_delta = nil
	self.fc_timer = nil
	self.fc_delay = 100
	self.object:set_fastcall(self.update,self)
end

function CDroneBinder:update(delta)
	object_binder.update(self,delta)
	local t = time_global()
	if (self.fc_timer and (self.fc_timer > t)) then
		return
	end
	self.fc_delta = self.fc_timer and (t - self.fc_timer + self.fc_delay) or 0
	self.fc_timer = t + self.fc_delay
	
	if (db.actor:active_slot() == 8) then
		self:RefreshMapSpot()
	end
	
	-- Power consumtion.
	self.power_timer = self.power_timer + self.fc_delta
	if (self.power_timer >= self.power_delay) then
		self.power_timer = self.power_timer - self.power_delay
		if (self.mem.condition and self.car:IsActiveEngine()) then
			self.mem.condition = clamp(self.mem.condition - self.power_cons,0,1)
			if not (self:PowerSufficient()) then
				self.car:SetfFuel(0)
				self.car:StopEngine()
			end
		end
	end
end

function CDroneBinder:ActorUpdate()
	if not (self:CanTakeControl()) then
		db.actor:detach_vehicle(true)
		return
	end
end

function CDroneBinder:PowerSufficient()
	if (self.mem.condition and (self.mem.condition < self.power_crit)) then
		return false
	end
	return true
end

function CDroneBinder:ActorInRange()
	return (db.actor:position():distance_to_sqr(self.object:position()) < math.pow(self.sig_radius,2))
end

function CDroneBinder:PayloadUpdate()
	local bid = self.attach_bone and self.object:bone_id(self.attach_bone)
	if (bid and bid ~= 65535) then
		local k = self:PayloadInfo()
		if (k) then
			if (self.object:get_attachment("payload") == nil) then
				self.object:add_attachment("payload",k.visual):set_parent_bone(bid)
				self.car:SetFlyWeightAdd(k.weight)
			end
		else
			if (self.object:get_attachment("payload")) then
				self.object:remove_attachment("payload")
				self.car:SetFlyWeightAdd(0)
			end
		end
	else
		URB_TAC:DEBUG("[%s] wrong parameters bone_name:%s bid:%s",self.object:name(),bone_name,bid)
	end
end

function CDroneBinder:PayloadInfo()
	local sec = self:ExplosiveSection()
	if (sec) then
		local visual = SYS_GetParam(0,sec,"visual")
		local weight = SYS_GetParam(2,sec,"weight",0)
		if (visual and weight) then
			local t = {}
			t.visual = visual
			t.weight = weight
			return t
		end
	end
end

function CDroneBinder:CanTakeControl()
	if not (self.object:alive()) then
		return false
	end
	if not (self:ActorInRange()) then
		return false
	end
	if not (self:PowerSufficient()) then
		return false
	end
	return true
end

function CDroneBinder:TakeControl()
	db.actor:detach_vehicle(true)
	db.actor:attach_vehicle(self.object,true)
end

function CDroneBinder:ExplosiveDetonate(who)
	local sec = self:ExplosiveSection()
	if (sec and self.object:alive()) then
		DRONE_MGR:SetAttachSection(self.object:id(),nil)
		self.car:LoadExplosiveSection(sec)
		self.car:SetInitiator(who and who:id() or self.oid)
		self.object:kill(who)
	end
end

function CDroneBinder:ExplosiveSection()
	return IED_MGR:ItemToObject(DRONE_MGR:GetAttachSection(self.object:id()))
end

function CDroneBinder:UpdateMapSpot(enable)
	level.map_remove_all_object_spots(self.oid)
	if not (enable) then
		return
	end
	
	if not (self.object:alive() and self.mem.owner_actor) then
		return
	end
	
	if (level.map_has_object_spot(self.oid,DRONE_MAP_SPOT) == 0) then
		level.map_add_object_spot(self.oid,DRONE_MAP_SPOT,"")
		self:RefreshMapSpot()
	end
end

function CDroneBinder:RefreshMapSpot()
	local txt = ui_item.get_sec_name(self.object:section())
	local num = db.actor:position():distance_to(self.object:position())
	txt = txt .. [[\n]] .. string.format(GT("drone_pda_info_range"),num)
	local sec = DRONE_MGR:GetAttachSection(self.object:id())
	if (sec) then
		txt = txt .. [[\n]] .. strformat(GT("drone_pda_info_attach"),ui_item.get_sec_short_name(sec))
	end
	level.map_change_spot_hint(self.oid,DRONE_MAP_SPOT,txt)
end

----------------------------------------------------------------------------------------------------
function CDroneBinder:reload(section)
	object_binder.reload(self,section)
end

function CDroneBinder:reinit()
	object_binder.reinit(self)
	db.storage[self.object:id()] = db.storage[self.object:id()] or {}
	self.st = db.storage[self.object:id()]
end

function CDroneBinder:net_spawn(se_abstract)
	if not (object_binder.net_spawn(self,se_abstract)) then
		return false
	end
	
	db.add_obj(self.object)
	add_object(self.object)
	self.object:set_callback(callback.death,self.death_callback,self)
	self.object:set_callback(callback.net_spawn_after,self.net_spawn_after,self)
	self:UpdateMapSpot(true)
	
	self:PayloadUpdate()
	
	SendScriptCallback("drone_on_net",self.object,true)
	return true
end

function CDroneBinder:net_spawn_after()
	if (self.mem) then
		if (self.mem.condition < self.power_crit) then
			self.car:SetfFuel(0)
		end
		if (self.mem.engine_on) then
			self.mem.engine_on = nil
			self.car:StartEngine()
		end
	end
end

function CDroneBinder:net_destroy()
	self:UpdateMapSpot(false)
	
	SendScriptCallback("drone_on_net",self.object,false)
	db.del_obj(self.object)
	del_object(self.object)
	self.object:set_callback(callback.death,nil)
	self.object:set_callback(callback.net_spawn_after,nil)
	object_binder.net_destroy(self)
end

function CDroneBinder:death_callback(obj,who)
	self:UpdateMapSpot(false)
	SendScriptCallback("drone_on_death",obj,who)
end

function CDroneBinder:net_save_relevant()
	return true
end

function CDroneBinder:save(packet)
	object_binder.save(self,packet)
	set_save_marker(packet,"save",false,"physics_binder")
	set_save_marker(packet,"save",true,"physics_binder")
	
	if (self.mem) then
		self.mem.engine_on = self.car:IsActiveEngine()
	end
end

function CDroneBinder:load(packet)
	object_binder.load(self,packet)
	set_save_marker(packet,"load",false,"physics_binder")
	set_save_marker(packet,"load",true,"physics_binder")
end

--[[----------------------------------------------------------------------------------------------------
	Combat
------------------------------------------------------------------------------------------------------]]
DRONE_COMBAT_RANGE = math.pow(25,2)

function distance_xz_sqr(a,b)
	return a:position():distance_to_xz_sqr(b:position())
end

function firing_line_of_sight_clear(npc,obj)
	if (npc and obj) then
		local pos = utils_obj.safe_bone_pos(npc,"bip01_spine2")
		local dir = vector():sub(obj:center(),pos):normalize()
		local ray = ray_pick(pos,dir,100,3,npc)
		if (ray:query()) then
			local who = ray:get_object()
			if (who and (who:id() == obj:id())) then
				return true
			end
		end
	end
	return false
end

function validate(npc,vid)
	if (vid and vid < 4294967295 and npc:accessible(vid)) then 
		return (db.used_level_vertex_ids[vid] == nil) or (db.used_level_vertex_ids[vid] == npc:id())
	end 
	return false
end 

function best_enemy_drone(npc)
	local o = nil
	local d = DRONE_COMBAT_RANGE
	for oid,obj in pairs(db.drone_objects) do
		local dis = distance_xz_sqr(npc,obj)
		if (obj:alive() and obj:get_car():IsActiveEngine() and (d > dis)) then
			---[[
			if (true) then
				o = obj
				d = dis
			end
			--]]
			local mem = DRONE_MGR:StorageById(oid)
			if (mem and mem.owner_actor) and (npc:relation(db.actor) == game_object.enemy) then
				o = obj
				d = dis
			end
		end
	end
	return o
end

function can_npc_fight_drone(npc,obj)
	-- Using holder.
	if (npc:get_attached_vehicle()) then
		return false
	end
	-- Prioritize creature enemies if seeing them or they are closer.
	local ene = npc:best_enemy()
	if (ene) then
		if (npc:see(ene)) then
			return false
		end
		if (distance_xz_sqr(npc,ene) < distance_xz_sqr(npc,obj)) then
			return false
		end
	end
	return true
end

function on_npc_vs_heli_eva(self,heli)
	if (self.mod_flags) then
		return
	end
	
	local obj = best_enemy_drone(self.object)
	if (obj and can_npc_fight_drone(self.object,obj)) then
		self.ret_value = true
		self.mod_flags = URB_TAC:Name()
	end
end

function on_npc_vs_heli_act(self)
	if (self.st.mod_flags ~= URB_TAC:Name()) then
		return
	end
	self.ret_value = false

	local obj = best_enemy_drone(self.object)
	if not (obj) then
		return
	end
	
	local npc = self.object
	if (npc:path_type() ~= game_object.level_path) then
		npc:set_path_type(game_object.level_path)
	end
	
	local see = firing_line_of_sight_clear(npc,obj)
	local dir = vector():sub(obj:center(),utils_obj.safe_bone_pos(npc,"bip01_r_finger02"))
	
	if (self.st.vid) then
		-- Move to cover.
		if (npc:level_vertex_id() ~= self.st.vid) then
			local new_state = see and "raid_fire" or "raid"
			state_mgr.set_state(npc,new_state,nil,nil,{look_dir = dir},{fast_set = true})
			axr_npc_vs_heli.lmove(npc,self.st.vid,self.st)
			return
		end
		
		-- Stay at cover.
		local new_state = see and "threat_fire" or "threat"
		state_mgr.set_state(npc,new_state,nil,nil,{look_dir = dir},{fast_set = true})
		
		self.st.__keep_point_until = self.st.__keep_point_until or (time_global() + math.random(3000,8000))
		if (self.st.__keep_point_until > time_global()) then
			return
		end
		-- Change cover.
		self.st.__keep_point_until = nil
		db.used_level_vertex_ids[self.st.vid] = nil
		self.st.vid = nil
	end
	
	if (self:try_go_cover(npc,obj:position(),10) == nil) then
		self:try_to_strafe(npc)
	end
end


--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	_G.DRONE_MGR = CDroneManager()
end