--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
------------------------------------------------------------------------------------------------------]]



--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
_G.URB_TAC = nil

class "CUrbanTacticsManager"
function CUrbanTacticsManager:__init()
	RegisterScriptCallback("on_key_release",self)
end

function CUrbanTacticsManager:Name()
	return "GT_urban_tactics"
end

function CUrbanTacticsManager:DEBUG(str,...)
	local func = debug.getinfo(2,"S").source
	local line = debug.getinfo(2,"l").currentline
	func = string.sub(func,#func - string.find(string.reverse(func),"\\") + 2,#func)
	local p = {...}
	if (p and (#p ~= 0)) then
		printf(string.format("%s: %s:%s | %s",self:Name(),tostring(func),tostring(line),str),...)
	else
		printf(string.format("%s: %s:%s | ",self:Name(),tostring(func),tostring(line)) .. "%s",str)
	end
end

function CUrbanTacticsManager:on_key_release(dik)
	if (dik == DIK_keys.DIK_NUMPAD6) then
		give_object_to_actor("grenade_flame",5)
		give_object_to_actor("grenade_m18",5)
		give_object_to_actor("grenade_rdg2",5)
		give_object_to_actor("grenade_explosive_charge",5)
	end
end

--[[----------------------------------------------------------------------------------------------------
	Utilities
------------------------------------------------------------------------------------------------------]]
function CUrbanTacticsManager:ObjectById(id)
	return id and (db.storage[id] and db.storage[id].object or level.object_by_id(id))
end

--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	_G.URB_TAC = CUrbanTacticsManager()
end