--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

local version = "1.0"

function on_option_change()
	if (ui_mcm) then
		ui_grenade_trajectory.TRAJECTORY_GRD = ui_mcm.get("gt/urban_tactics/trajectory_grd")
		ui_grenade_trajectory.TRAJECTORY_LCH = ui_mcm.get("gt/urban_tactics/trajectory_lch")
		
		ied_gameplay.KEY_DETONATE = ui_mcm.get("gt/urban_tactics/key_ied_detonate") or ied_gameplay.KEY_DETONATE_DEF
		drone_gameplay.KEY_DETONATE = ui_mcm.get("gt/urban_tactics/key_drone_detonate") or drone_gameplay.KEY_DETONATE_DEF
	end
end

function on_mcm_load()
	return
	{
		id	= "urban_tactics",
		sh = true,
		gr = {
			{id = "tittle_line_1",type = "line"},
			{id = "tittle_name",type = "title",text = strformat(GT("ui_mcm_gt_urban_tactics_tittle"),version)},
			{id = "tittle_line_2",type = "line"},
			
			{id = "trajectory_grd",type = "check",val = 1,def = true},
			{id = "trajectory_lch",type = "check",val = 1,def = true},
			
			{id = "ied_name",type = "title",text = "ui_mcm_gt_urban_tactics_ied_name"},
			{id = "ied_desc",type = "desc",text = "ui_mcm_gt_urban_tactics_ied_desc"},
			{id = "key_ied_detonate",type = "key_bind",val = 2,def = ied_gameplay.KEY_DETONATE_DEF},
			{id = "ied_line",type = "line"},
			
			{id = "drone_name",type = "title",text = "ui_mcm_gt_urban_tactics_drone_name"},
			{id = "drone_desc",type = "desc",text = "ui_mcm_gt_urban_tactics_drone_desc"},
			{id = "key_drone_detonate",type = "key_bind",val = 2,def = drone_gameplay.KEY_DETONATE_DEF},
			{id = "drone_line",type = "line"},
		}
	}, "gt"
end

function on_game_start()
	RegisterScriptCallback("on_option_change",on_option_change)
	on_option_change()
end