--[[----------------------------------------------------------------------------------------------------
	GhenTuong
	Discord: GhenTuong#1278
	Twitter: https://twitter.com/GhenTuong
	To do:
------------------------------------------------------------------------------------------------------]]
local GT = game.translate_string

_G.AddScriptCallback("drone_on_net")
_G.AddScriptCallback("drone_on_death")

local DRONE_MAP_SPOT = "drone_map_spot"
local DRONE_NVG_PPE = 555242 --URB

KEY_DETONATE_DEF = DIK_keys.DIK_J
KEY_DETONATE = KEY_DETONATE_DEF

db.drone_objects = {}

function add_object(obj)
	db.drone_objects[obj:id()] = obj
end

function del_object(obj)
	db.drone_objects[obj:id()] = nil
end

--[[----------------------------------------------------------------------------------------------------
	Manager
------------------------------------------------------------------------------------------------------]]
_G.DRONE_MGR = nil

class "CDroneManager"
function CDroneManager:__init()
	self.DRONE_VAR = {}
	self.DRONE_MEM = {}
	
	self.cfg_item_to_object = {}
	self.cfg_object_to_item = {}
	
	do
		local ini = ini_file([[items\settings\deploy.ltx]])
		if (ini:section_exist("drones")) then
			for idx,val in pairs(utils_data.collect_section(ini,"drones",true)) do
				if (ini_sys:section_exist(idx) and ini_sys:section_exist(val)) then
					self.cfg_item_to_object[idx] = val
					self.cfg_object_to_item[val] = idx
				else
					URB_TAC:DEBUG("Wrong parameters [%s] %s",idx,val)
				end
			end
		end
	end
	
	self.nvg_drone = false
	self.nvg_timer = 0
	
	RegisterScriptCallback("save_state",self)
	RegisterScriptCallback("load_state",self)
	RegisterScriptCallback("server_object_on_register",self)
	RegisterScriptCallback("server_object_on_unregister",self)
	RegisterScriptCallback("actor_on_first_update",self)
	RegisterScriptCallback("map_spot_menu_add_property",self)
	RegisterScriptCallback("map_spot_menu_property_clicked",self)
	
	RegisterScriptCallback("actor_on_attach_vehicle",self)
	RegisterScriptCallback("actor_on_detach_vehicle",self)
	
	RegisterScriptCallback("GUI_on_show",self)
	RegisterScriptCallback("GUI_on_hide",self)
	RegisterScriptCallback("actor_on_net_destroy",self)
	RegisterScriptCallback("ActorMenu_on_item_drag_drop",self)
	
	RegisterScriptCallback("on_npc_vs_heli_eva",on_npc_vs_heli_eva)
	RegisterScriptCallback("on_npc_vs_heli_act",on_npc_vs_heli_act)
	
	rax_icon_layers.register("drone_icon_layer",drone_icon_layer)
end

function CDroneManager:save_state(m_data)
	m_data.GT_DRONE_VAR = self.DRONE_VAR
	m_data.GT_DRONE_MEM = self.DRONE_MEM
end

function CDroneManager:load_state(m_data)
	self.DRONE_VAR = m_data.GT_DRONE_VAR or {}
	self.DRONE_MEM = m_data.GT_DRONE_MEM or {}
end

function CDroneManager:actor_on_first_update()
	for id,se in pairs(db.se_drones) do
		if not (simulation_objects.is_on_the_actor_level(se)) then
			URB_TAC:DEBUG("Release drone for not in actor level [%s]",se:name())
			alife_release(se)
		end
	end
end

function CDroneManager:server_object_on_register(se)
	local sec = se:section_name()
	if (self.cfg_item_to_object[sec] or self.cfg_object_to_item[sec]) then
		if (self.DRONE_MEM[se.id] == nil) then
			self.DRONE_MEM[se.id] = {}
			URB_TAC:DEBUG("DRONE_MEM[%s] Storage Create",se:name())
		end
	end
end

function CDroneManager:server_object_on_unregister(se)
	local sec = se:section_name()
	if (self.cfg_item_to_object[sec] or self.cfg_object_to_item[sec]) then
		self.DRONE_MEM[se.id] = nil
		URB_TAC:DEBUG("DRONE_MEM[%s] Storage Delete",se:name())
	end
end

function CDroneManager:IsDroneSection(sec)
	return sec and (SYS_GetParam(0,sec,"class") == "_S_DRONE") and true or false
end

function CDroneManager:ItemToObject(sec)
	return sec and self.cfg_item_to_object[sec]
end

function CDroneManager:ObjectToItem(sec)
	return sec and self.cfg_object_to_item[sec]
end

function CDroneManager:StorageById(oid)
	return oid and self.DRONE_MEM[oid]
end

function CDroneManager:StorageCopy(src_id,dst_id)
	local src = self:StorageById(src_id)
	local dst = self:StorageById(dst_id)
	assert(src,strformat("[%s] src not exist",src_id))
	assert(dst,strformat("[%s] dst not exist",dst_id))
	
	dst.attach_sec = src.attach_sec
end

function CDroneManager:Create(prs,owner_actor)
	local sec = prs and prs.sec
	local pos = prs and prs.pos
	local vid = prs and prs.vid
	local gid = prs and prs.gid
	local ang = prs and prs.ang
	local itm = prs and prs.itm
	if (sec and pos and vid and gid and ang and self:IsDroneSection(sec)) then
		local se = alife_create(sec,pos,vid,gid)
		se.angle = vector():set(ang.y,ang.x,ang.z)
		if (itm) then
			self:StorageCopy(itm:id(),se.id)
			self:StorageById(se.id).condition = itm:condition()
		end
		if (owner_actor) then
			self:StorageById(se.id).owner_actor = true
		end
		return true
	end
	URB_TAC:DEBUG("Wrong parameters %s %s %s %s %s",sec,pos,vid,gid,ang)
	return false
end

function CDroneManager:DroneAttach(obj,itm)
	if not (self:ItemToObject(obj:section()) and IED_MGR:ItemToObject(itm:section())) then
		return
	end
	local mem = self:StorageById(obj:id())
	if (mem.attach_sec == nil) then
		mem.attach_sec = itm:section()
		itms_manager.play_item_sound(itm,0.75)
		alife_release(itm)
	end
end

function CDroneManager:DroneDetach(obj)
	if not (self:ItemToObject(obj:section())) then
		return
	end
	local mem = self:StorageById(obj:id())
	if (mem.attach_sec) then
		alife_create_item(mem.attach_sec,db.actor)
		mem.attach_sec = nil
	end
end

function CDroneManager:SetServerItemCondition(itm,num)
	if (itm and num) then
		local pkt = utils_stpk.get_item_data(itm)
		pkt.condition = clamp(num,0,1)
		utils_stpk.set_item_data(pkt,itm)
	end
end

function CDroneManager:map_spot_menu_add_property(property_ui,oid,lvl)
	local obj = db.drone_objects[oid]
	if (obj) then
		property_ui:AddItem(GT("drone_pda_cmd_control"))
	end
end

function CDroneManager:map_spot_menu_property_clicked(property_ui,oid,lvl,sec)
	local obj = db.drone_objects[oid]
	if (obj) then
		if (sec == GT("drone_pda_cmd_control")) then
			if (obj:binded_object():CanTakeControl()) then
				db.actor:activate_slot(0)
				obj:binded_object():TakeControl()
			end
		end
	end
end

function CDroneManager:actor_on_attach_vehicle(obj)
	if (IsDrone(obj)) then
		hud_camfpv_active(obj)
		self:SetMinimap(false)
		
		local mgr = obj:binded_object()
		
		--NVG
		do
			item_device.set_nightvision(itm and itm:section(),false)
			local itm = db.actor:item_in_slot(10)
			if (itm) then
				self.DRONE_VAR.torch_itm = itm:id()
				db.actor:move_to_ruck(itm)
			end
			
			self:SetDroneNVG(mgr.cfg_nvg,mgr.mem.nvg_enable)
		end
		
		RegisterScriptCallback("actor_on_update",self)
		RegisterScriptCallback("on_key_press",self)
		RegisterScriptCallback("on_before_key_press",self)
		RegisterScriptCallback("on_before_key_release",self)
	end
end

function CDroneManager:actor_on_detach_vehicle(obj)
	if (IsDrone(obj)) then
		hud_camfpv_remove()
		self:SetMinimap(true)
		
		local mgr = obj:binded_object()
		
		--NVG
		do
			self:SetDroneNVG(mgr.cfg_nvg,false)
			
			local itm = URB_TAC:object_by_id(self.DRONE_VAR.torch_itm)
			self.DRONE_VAR.torch_itm = nil
			if (itm and SYS_GetParam(0,itm:section(),"class") == "TORCH_S") then
				db.actor:move_to_slot(itm,10)
			end
		end
		
		UnregisterScriptCallback("actor_on_update",self)
		UnregisterScriptCallback("on_key_press",self)
		UnregisterScriptCallback("on_before_key_press",self)
		UnregisterScriptCallback("on_before_key_release",self)
	end
end

function CDroneManager:actor_on_update()
	local obj = db.actor:get_attached_vehicle()
	if (obj and IsDrone(obj)) then
		obj:binded_object():actor_on_update()
	end
end

function CDroneManager:on_key_press(dik)
	if (dik == KEY_DETONATE) then
		local obj = db.actor:get_attached_vehicle()
		local mgr = obj and IsDrone(obj) and obj:binded_object()
		if (mgr) then
			mgr:ExplosiveDetonate(db.actor)
		end
	end
	
	if (dik == bind_to_dik(key_bindings.kNIGHT_VISION)) then
		local obj = db.actor:get_attached_vehicle()
		local mgr = obj and IsDrone(obj) and obj:binded_object()
		if (mgr and mgr.cfg_nvg) then
			if (self.nvg_timer < time_global()) then
				self.nvg_timer = time_global() + 500
				if (mgr.mem.nvg_enable) then
					mgr.mem.nvg_enable = nil
					utils_obj.play_sound([[interface\inv_nv_off]])
				else
					mgr.mem.nvg_enable = true
					utils_obj.play_sound([[interface\inv_nv_start]])
				end
				self:SetDroneNVG(mgr.cfg_nvg,mgr.mem.nvg_enable)
			end
		end
	end
end

function CDroneManager:on_before_key_press(dik,bind,dis,flags)
	if (dik == bind_to_dik(key_bindings.kINVENTORY)) then
		flags.ret_value = false
	end
end

function CDroneManager:on_before_key_release(dik,bind,dis,flags)
	if (dik == bind_to_dik(key_bindings.kINVENTORY)) then
		flags.ret_value = false
	end
end

function CDroneManager:GUI_on_show()
	hud_deploy_update()
	hud_camfpv_update()
end

function CDroneManager:GUI_on_hide()
	hud_deploy_update()
	hud_camfpv_update()
end

function CDroneManager:actor_on_net_destroy()
	hud_deploy_remove()
	hud_camfpv_remove()
end

function CDroneManager:ActorMenu_on_item_drag_drop(itm,obj,slot_from,slot_next)
	if not (slot_from == EDDListType.iActorBag and slot_next == EDDListType.iActorBag) then
        return
    end
	local sec = self:ItemToObject(obj:section())
	local str = sec and SYS_GetParam(0,sec,"attach_bone")
	if not (str and str ~= "" and str ~= "nil") then
		return
	end
	self:DroneDetach(obj)
	self:DroneAttach(obj,itm)
end

function drone_icon_layer(cell,obj,sec)
	if not (cell.showcase == 0) then
		return
	end
	if not (DRONE_MGR:ItemToObject(sec)) then
		return
	end
	local mem = DRONE_MGR:StorageById(obj:id())
	if not (mem.attach_sec) then
		return
	end

	local icon_scale = 0.5
	
	local obj_axis = utils_xml.get_item_axis(sec)
	local itm_axis = utils_xml.get_item_axis(mem.attach_sec)
	return {
		icon_layer = mem.attach_sec,
		icon_layer_x = 0,
		icon_layer_y = obj_axis.h / icon_scale - itm_axis.h,
		icon_layer_scale = icon_scale,
	}
end

function CDroneManager:SetMinimap(state)
	if (ui_options.get([[video/hud/show_minimap]]) == false) then
		return
	end
	if (state) then
		ActorMenu.get_maingame().UIZoneMap.disabled = false
		ActorMenu.get_maingame().UIMotionIcon:Show(true)
	else
		ActorMenu.get_maingame().UIZoneMap.disabled = true
		ActorMenu.get_maingame().UIMotionIcon:Show(false)
	end
end

function CDroneManager:GetDroneNVG()
	return self.nvg_drone and true or false
end

function CDroneManager:SetDroneNVG(cfg,state)
	if (state) and (not self.nvg_drone) and (cfg) then
		level.add_pp_effector(cfg.ppe .. ".ppe",DRONE_NVG_PPE,true)
		game.set_nv_lumfactor(cfg.lum)
		self.nvg_drone = true
	end
	if (not state) and (self.nvg_drone) then
		level.remove_pp_effector(DRONE_NVG_PPE)
		game.set_nv_lumfactor(0)
		self.nvg_drone = false
	end
end

--[[----------------------------------------------------------------------------------------------------
	Item
------------------------------------------------------------------------------------------------------]]
function drone_deploy_desc(obj)
	return GT("drone_item_deploy")
end

function drone_deploy_func(obj)
	hud_deploy_active(obj)
end

function drone_detach_desc(obj)
	local mem = DRONE_MGR:StorageById(obj:id())
	if (mem.attach_sec) then
		return strformat(GT("drone_item_detach"),ui_item.get_sec_short_name(mem.attach_sec))
	end
end

function drone_detach_func(obj)
	DRONE_MGR:DroneDetach(obj)
end

function deploy_condition()
	if not (db.actor:alive()) then
		return false
	end
	if (db.actor:get_attached_vehicle()) then
		return false
	end
	if (db.actor:is_talking()) then
		return false
	end
	if (IsMoveState("mcClimb")) then
		return false
	end
	return true
end

function on_before_hit(obj,shit,bone_id)
	return true
end

function on_before_use(obj,cam_pos,cam_dir,act_pos)
	CreateTimeEvent(obj:id(),"pickup",0,pick_up_time_event,obj:id())
	return false
end

function pick_up_time_event(oid)
	local obj = db.drone_objects[oid]
	local sec = obj and DRONE_MGR:ObjectToItem(obj:section())
	if (sec) then
		local mem = DRONE_MGR:StorageById(obj:id())
		local se = alife_create_item(sec,db.actor,{cond = clamp(mem.condition or 1,0,1)})
		DRONE_MGR:StorageCopy(obj:id(),se.id)
		alife_release(obj)
		news_manager.relocate_item(db.actor,"in",sec)
	end
	return true
end

function on_explode(obj)
	if (obj:binded_object()) then
		obj:binded_object():UpdateMapSpot(false)
	end
end

--[[----------------------------------------------------------------------------------------------------
	UIDeploy
------------------------------------------------------------------------------------------------------]]
HUD_DEPLOY = nil

function hud_deploy_active(obj)
	if (HUD_DEPLOY == nil) then
		HUD_DEPLOY = UIDeploy(obj)
		get_hud():AddDialogToRender(HUD_DEPLOY)
		RegisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_remove()
	if (HUD_DEPLOY) then
		get_hud():RemoveDialogToRender(HUD_DEPLOY)
		HUD_DEPLOY = nil
		UnregisterScriptCallback("on_key_press",on_key_press)
	end
end

function hud_deploy_update()
	if (HUD_DEPLOY) then
		HUD_DEPLOY:Update(true)
	end
end

function on_key_press(dik)
	if (HUD_DEPLOY) then
		HUD_DEPLOY:OnKeyPress(dik)
	end
end

class "UIDeploy" (CUIScriptWnd)
function UIDeploy:__init(obj) super(obj)
	self:SetAutoDelete(true)
	
	self.oid = obj:id()
	self.sec = obj:section()
	self.vis = self:GetAttachmentVisual(obj)
	self.atm_name = "deploy_drone"
	self.dist_def = 1
	self.dist_max = 3
	
	self.radius_min = 0.5
	self.radius_max = 1.0
	self.height_min = -1.8
	self.height_max = 0.0
	
	self.exclusive_radius = 0.4
	self.exclusive_height = 0.05
	self.vec_up = vector():set(VEC_Y)
	self.vec_dw = vector():set(self.vec_up):invert()
	
	if (self:FDDA() or self:FDDA_REDONE()) then
		self.active = nil
		self.hiding = false
		
		if (self:FDDA()) then
			zzz_ea_addon_backpack.active_slot = nil
			zzz_ea_addon_backpack.item_after_backpack = nil
		end
		
		if (self:FDDA_REDONE()) then
			lam2.cur_slot = nil
		end
	else
		self.active = db.actor:active_slot()
		self.hiding = (self.active ~= 0) and true or false
	end
	
	db.actor:activate_slot(0)
	hide_hud_inventory()
end

function UIDeploy:__finalize()
end

function UIDeploy:Update()
	CUIScriptWnd.Update(self)
	
	if not (main_hud_shown()) then
		return self:Close()
	end
	
	if not (deploy_condition()) then
		return self:Close()
	end
	
	if not (URB_TAC:object_by_id(self.oid)) then
		return self:Close()
	end
	
	if not (self.vis) then
		return self:Close()
	end
	
	if (self.hiding) then
		if (db.actor:active_slot() == 0) then
			self.hiding = false
		elseif (db.actor:active_slot() ~= self.active) then
			return self:Close()
		end
	else
		if (db.actor:active_slot() ~= 0) then
			return self:Close()
		end
	end
	
	self.pos = self:GetDeployPosition()
	
	if (self.pos) then
		if (level.get_attachment(self.atm_name) == nil) then
			level.add_attachment(self.atm_name,self.vis)
			--level.add_attachment(self.atm_name,self.vis):set_shader(-1,[[models\selflight_det]],nil)
		end
		local atm = level.get_attachment(self.atm_name)
		if (atm) then
			atm:set_position(self.pos)
			local h = math.deg(device().cam_dir:getH())
			atm:set_rotation(h,0,0)
		end
	else
		if (level.get_attachment(self.atm_name)) then
			level.remove_attachment(self.atm_name)
		end
	end
end

function UIDeploy:FDDA()
	return zzz_ea_addon_backpack and true or false
end

function UIDeploy:FDDA_REDONE()
	return lam2 and true or false
end

function UIDeploy:Deploy()
	if (self.hiding) then
		return
	end
	local atm = level.get_attachment(self.atm_name)
	local xfm = atm and atm:get_transform()
	if not (xfm) then
		return
	end
	local obj = URB_TAC:object_by_id(self.oid)
	local k = {}
	k.sec = DRONE_MGR:ItemToObject(obj:section())
	k.pos = vector():set(xfm.c)
	k.vid = db.actor:level_vertex_id()
	k.gid = db.actor:game_vertex_id()
	k.ang = xfm:getHPB()
	k.itm = obj
	if (DRONE_MGR:Create(k,true)) then
		itms_manager.play_item_sound(obj,0.75)
		news_manager.relocate_item(db.actor,"out",obj:section())
		alife_release(obj)
	end
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:GetAttachmentVisual(obj)
	local sec = obj and DRONE_MGR:ItemToObject(obj:section())
	return sec and SYS_GetParam(0,sec,"visual")
end

function UIDeploy:GetDeployPosition()
	local pos = device().cam_pos
	local dir = vector():set(device().cam_dir.x,0,device().cam_dir.z):normalize()
	local ray = ray_pick(pos,dir,self.dist_def,2,db.actor)
	if (ray:query()) then
		return
	end
	local vec = vector():mad(pos,dir,self.dist_def)
	local tmp = pos.y - db.actor:position().y + 0.5
	local ray = ray_pick(vec,self.vec_dw,tmp,2,db.actor)
	if (ray:query()) then
		return vector():mad(vec,self.vec_dw,ray:get_distance())
	end
end

function UIDeploy:ResumeActive()
	if (self.active and self.active ~= 0) then
		db.actor:activate_slot(self.active)
	end
end

function UIDeploy:Cancel()
	self:ResumeActive()
	return self:Close()
end

function UIDeploy:Close()
	if (level.get_attachment(self.atm_name)) then
		level.remove_attachment(self.atm_name)
	end
	hud_deploy_remove()
end

function UIDeploy:OnKeyPress(dik)
	if (dik == DIK_keys.MOUSE_1) then
		return self:Deploy()
	end
	if (dik == DIK_keys.MOUSE_2) then
		return self:Cancel()
	end
end

--[[----------------------------------------------------------------------------------------------------
	UICamfpv
------------------------------------------------------------------------------------------------------]]
HUD_CAMFPV = nil

function hud_camfpv_active(obj)
	if (HUD_CAMFPV == nil) then
		HUD_CAMFPV = UICamfpv(obj)
		get_hud():AddDialogToRender(HUD_CAMFPV)
	end
end

function hud_camfpv_remove()
	if (HUD_CAMFPV) then
		get_hud():RemoveDialogToRender(HUD_CAMFPV)
		HUD_CAMFPV = nil
	end
end

function hud_camfpv_update()
	if (HUD_CAMFPV) then
		HUD_CAMFPV:Update(true)
	end
end

class "UICamfpv" (CUIScriptWnd)
function UICamfpv:__init(obj) super(obj)
	self:SetAutoDelete(true)
	self.xml = CScriptXmlInit()
	self.xml:ParseFile("ui_drone_camfpv.xml")
	
	self.obj = obj
	self.car = obj:get_car()
	self.mgr = obj:binded_object()
	
	self.CLR_G = utils_xml.get_color("d_green",true)
	self.CLR_Y = utils_xml.get_color("pda_yellow",true)
	self.CLR_R = utils_xml.get_color("d_red",true)
	self.INV_Y = vector():set(0,1,0):invert()
	
	self.CLR_0 = GetARGB(255,250,250,250)
	self.CLR_1 = GetARGB(255,0,0,0)
	
	self.hud = self.xml:InitStatic("hud",self)
	self:ApplyScreenRatio(self.hud)
	
	self.cursor = self.xml:InitStatic("cursor",self)
	self:ApplyScreenRatio(self.cursor)
	
	self.status = self.xml:InitStatic("status",self)
	self:ApplyScreenRatio(self.status,false)
	self.status:SetTextureColor(GetARGB(128,0,0,0))
	
	self.dialog = self.xml:InitStatic("status:dialog",self.status)
	self:ApplyScreenRatio(self.dialog,true)
	
	self.sig_img = self.xml:InitProgressBar("status:dialog:signal_img",self.dialog)
	self.sig_bar = self.xml:InitProgressBar("status:dialog:signal_bar",self.dialog)
	self:ApplyScreenRatio(self.sig_img,true)
	self:ApplyScreenRatio(self.sig_bar,true)
	self:ApplyScreenRatio(self.sig_img:GetProgressStatic(),true)
	self:ApplyScreenRatio(self.sig_bar:GetProgressStatic(),true)
	self.sig_img:SetColor(utils_xml.get_color("ui_gray_1",true))
	self.sig_max = math.floor(self.sig_bar:GetRange_max())
	
	self.btr_txt = self.xml:InitTextWnd("status:dialog:battery_txt",self.dialog)
	self.btr_img = self.xml:InitStatic("status:dialog:battery_img",self.dialog)
	self.btr_bar = self.xml:InitProgressBar("status:dialog:battery_bar",self.dialog)
	self:ApplyScreenRatio(self.btr_txt,true)
	self:ApplyScreenRatio(self.btr_img,true)
	self:ApplyScreenRatio(self.btr_bar,true)
	self:ApplyScreenRatio(self.btr_bar:GetProgressStatic(),true)
	
	self.compass = self.xml:InitStatic("compass",self)
	self.compass_bgr = self.xml:InitStatic("compass:compass_bgr",self.compass)
	self.compass_img = self.xml:InitStatic("compass:compass_img",self.compass)
	self:ApplyScreenRatio(self.compass_bgr,true)
	self:ApplyScreenRatio(self.compass_img,true)
	self.compass_bgr:SetTextureColor(GetARGB(128,0,0,0))
	self.compass_img:EnableHeading(true)
	
	self.side_string_bgr = self.xml:InitTextWnd("side_string",self)
	self:ApplyScreenRatio(self.side_string_bgr)
	self.side_string_txt = self.xml:InitTextWnd("side_string",self)
	self:ApplyScreenRatio(self.side_string_txt)
	local vec = self.side_string_bgr:GetWndPos()
	self.side_string_bgr:SetWndPos(vector2():set(vec.x + 2 * self:ScreenRatio(),vec.y + 2))
	self.side_string_bgr:SetTextColor(GetARGB(255,0,0,0))
end

function UICamfpv:__finalize()
end

function UICamfpv:Update()
	CUIScriptWnd.Update(self)
	
	if not (main_hud_shown()) then
		self:Show(false)
		return
	end
	self:Show(true)
	
	-- Cursor
	do
		local ang = self.car:VisualCamera_GetDesireAngle()
		local vec = vector2()
		vec.x = 512 - (512 * clamp((ang.y - self.car:VisualCamera_GetRotYCur()) / self:GetFovHorz(),-1,1))
		vec.y = 384 - (384 * clamp((ang.x - self.car:VisualCamera_GetRotXCur()) / self:GetFovVert(),-1,1))
		self.cursor:SetWndPos(vec)
	end
	-- Signal
	do
		local num = self:SignalPower()
		self.sig_img:SetProgressPos(self.sig_max - num)
		self.sig_bar:SetProgressPos(num)
		self.sig_bar:SetColor(self:SignalColor(num))
	end
	-- Battery
	do
		local num = clamp(self.mgr.mem and self.mgr.mem.condition or 1,0,1) * 100
		local clr = self:BatteryColor(num)
		self.btr_txt:SetText(strformat([[%s%]],math.floor(num)))
		self.btr_bar:SetProgressPos(num)
		self.btr_txt:SetTextColor(clr)
		self.btr_img:SetTextureColor(clr)
		self.btr_bar:SetColor(clr)
	end
	-- Compass
	do
		self.compass_img:SetHeading(self.car:VisualCamera_GetRotYCur())
	end
	-- Infomation
	do
		local txt = ""
		txt = txt .. string.format(GT("drone_hud_info_zoom"),self.car:GetZoomFactor())
		if (self.mgr.cfg_nvg) then
			if (self.mgr.mem.nvg_enable) then
				txt = txt .. [[\n]] .. GT("drone_hud_info_nvg1")
			else
				txt = txt .. [[\n]] .. GT("drone_hud_info_nvg0")
			end
		end
		if (self.mgr.attach_bone) then
			if (self.mgr.mem.attach_sec) then
				txt = txt .. [[\n]] .. string.format(GT("drone_hud_info_atm1"),ui_item.get_sec_name(self.mgr.mem.attach_sec))
			else
				txt = txt .. [[\n]] .. GT("drone_hud_info_atm0")
			end
		end
		self.side_string_txt:SetText(txt)
		self.side_string_bgr:SetText(txt)
	end
end

function UICamfpv:SignalPower()
	local num = math.min(db.actor:position():distance_to(self.obj:position()),self.mgr.sig_radius)
	local sig = self.mgr.sig_radius * 0.5
	return math.max(0,math.ceil(self.sig_max * (sig - num) / sig))
end

function UICamfpv:SignalColor(num)
	if (num <= 1) then
		return self.CLR_R
	end
	if (num <= 2) then
		return self.CLR_Y
	end
	return self.CLR_G
end

function UICamfpv:BatteryColor(num)
	if (num < 20) then
		return self.CLR_R
	end
	if (num < 50) then
		return self.CLR_Y
	end
	return self.CLR_G
end

function UICamfpv:Close()
	self:Show(false)
	hud_camfpv_remove()
end

function UICamfpv:ScreenRatio()
	return (1024/768)/(device().width/device().height)
end

function UICamfpv:ApplyScreenRatio(ele,pos)
	ele:SetWndSize(vector2():set(ele:GetWidth()*self:ScreenRatio(),ele:GetHeight()))
	if (pos) then
		ele:SetWndPos(vector2():set(ele:GetWndPos().x*self:ScreenRatio(),ele:GetWndPos().y))
	end
end

function UICamfpv:GetFovHorz()
	return math.rad(device().fov)
end

function UICamfpv:GetFovVert()
	local dev = device()
	return math.atan(math.tan(math.rad(dev.fov))*dev.height/dev.width)
end

--[[----------------------------------------------------------------------------------------------------
	CDroneBinder
------------------------------------------------------------------------------------------------------]]
function init(obj)
	obj:bind_object(CDroneBinder(obj))
end

class "CDroneBinder" (object_binder)
function CDroneBinder:__init(obj) super(obj)
	db.storage[self.object:id()] = {}
	self.oid = self.object:id()
	self.car = self.object:get_car()
	self.mem = DRONE_MGR:StorageById(self.oid)
	
	self.attach_bone = SYS_GetParam(0,self.object:section(),"attach_bone")
	if (self.attach_bone == "") or (self.attach_bone == "nil") then
		self.attach_bone = nil
	end
	
	do
		local sec = self:ExplosiveSection()
		local visual = sec and SYS_GetParam(0,sec,"visual")
		local weight = sec and SYS_GetParam(2,sec,"weight",0)
		if (visual and weight) then
			self.attach_info = {}
			self.attach_info.visual = visual
			self.attach_info.weight = weight
		end
	end
	
	do
		local str = SYS_GetParam(0,self.object:section(),"nv_effect")
		local tmp = str and str_explode(str,",")
		local lum = tonumber(tmp and tmp[1])
		local ppe = tmp and tmp[2]
		if (lum and ppe) then
			self.cfg_nvg = {}
			self.cfg_nvg.lum = lum
			self.cfg_nvg.ppe = ppe
		end
	end
	
	local num = SYS_GetParam(2,self.object:section(),"power_time") or 0
	self.power_cons = (num > 0) and (1 / (num * self:AttachPenaltyScale())) or 0
	self.power_crit = SYS_GetParam(2,self.object:section(),"power_crit") or 0
	self.sig_radius = SYS_GetParam(2,self.object:section(),"sig_radius") or 10000
	
	self.power_timer = 0
	self.power_delay = 1000
	
	self.fc_delta = nil
	self.fc_timer = nil
	self.fc_delay = 100
	self.object:set_fastcall(self.update,self)
end

function CDroneBinder:update(delta)
	object_binder.update(self,delta)
	local t = time_global()
	if (self.fc_timer and (self.fc_timer > t)) then
		return
	end
	self.fc_delta = self.fc_timer and (t - self.fc_timer + self.fc_delay) or 0
	self.fc_timer = t + self.fc_delay
	
	if (db.actor:active_slot() == 8) then
		self:RefreshMapSpot()
	end
	
	-- Power consumtion.
	self.power_timer = self.power_timer + self.fc_delta
	if (self.power_timer >= self.power_delay) then
		self.power_timer = self.power_timer - self.power_delay
		if (self.mem.condition and self.car:IsActiveEngine()) then
			self.mem.condition = clamp(self.mem.condition - self.power_cons,0,1)
			if not (self:PowerSufficient()) then
				self.car:SetfFuel(0)
				self.car:StopEngine()
			end
		end
	end
end

function CDroneBinder:actor_on_update()
	if (self:CanTakeControl() == false) then
		db.actor:detach_vehicle(true)
		return
	end
end

function CDroneBinder:PowerSufficient()
	if (self.mem.condition and (self.mem.condition < self.power_crit)) then
		return false
	end
	return true
end

function CDroneBinder:ActorInRange()
	return (db.actor:position():distance_to_sqr(self.object:position()) < math.pow(self.sig_radius,2))
end

function CDroneBinder:AttachPenaltyScale()
	local num = SYS_GetParam(2,self.object:section(),"inv_weight") or 1
	assert(num > 0,strformat("[%s] inv_weight invalid.",self.object:section()))
	return (num) / (num + (self.attach_info and self.attach_info.weight or 0))
end

function CDroneBinder:AttachUpdate()
	local bid = self.attach_bone and self.object:bone_id(self.attach_bone)
	if (bid and bid ~= 65535) and (self.attach_info) then
		if (self.object:get_attachment("payload") == nil) then
			self.object:add_attachment("payload",self.attach_info.visual):set_parent_bone(bid)
			self.car:SetFlyWeightAdd(self.attach_info.weight)
		end
	else
		if (self.object:get_attachment("payload")) then
			self.object:remove_attachment("payload")
			self.car:SetFlyWeightAdd(0)
		end
	end
	self.car:CCarDrone_SetPowerEfficiency(self:AttachPenaltyScale())
end

function CDroneBinder:CanTakeControl()
	if not (self.object:alive()) then
		return false
	end
	if not (self:ActorInRange()) then
		return false
	end
	if not (self:PowerSufficient()) then
		return false
	end
	return true
end

function CDroneBinder:TakeControl()
	db.actor:detach_vehicle(true)
	db.actor:attach_vehicle(self.object,true)
end

function CDroneBinder:ExplosiveDetonate(who)
	local sec = self:ExplosiveSection()
	if (sec and self.object:alive()) then
		self.mem.attach_sec = nil
		self.car:LoadExplosiveSection(sec)
		self.car:SetInitiator(who and who:id() or self.oid)
		self.object:kill(who)
	end
end

function CDroneBinder:ExplosiveSection()
	return IED_MGR:ItemToObject(self.mem.attach_sec)
end

function CDroneBinder:UpdateMapSpot(enable)
	level.map_remove_all_object_spots(self.oid)
	
	if (enable and self.object:alive() and self.mem.owner_actor) then
		if (level.map_has_object_spot(self.oid,DRONE_MAP_SPOT) == 0) then
			level.map_add_object_spot(self.oid,DRONE_MAP_SPOT,"")
			self:RefreshMapSpot()
		end
	end
end

function CDroneBinder:RefreshMapSpot()
	local txt = ui_item.get_sec_name(self.object:section())
	local num = db.actor:position():distance_to(self.object:position())
	txt = txt .. [[\n]] .. string.format(GT("drone_pda_info_range"),num)
	level.map_change_spot_hint(self.oid,DRONE_MAP_SPOT,txt)
end

----------------------------------------------------------------------------------------------------
function CDroneBinder:reload(section)
	object_binder.reload(self,section)
end

function CDroneBinder:reinit()
	object_binder.reinit(self)
	if (db.storage[self.object:id()]) then
		db.storage[self.object:id()] = {}
	end
	self.st = db.storage[self.object:id()]
end

function CDroneBinder:net_spawn(se_abstract)
	if not (object_binder.net_spawn(self,se_abstract)) then
		return false
	end
	
	db.add_obj(self.object)
	add_object(self.object)
	self.object:set_callback(callback.death,self.death_callback,self)
	self.object:set_callback(callback.net_spawn_after,self.net_spawn_after,self)
	self:UpdateMapSpot(true)
	
	SendScriptCallback("drone_on_net",self.object,true)
	return true
end

function CDroneBinder:net_spawn_after()
	if (self.mem.condition < self.power_crit) then
		self.car:SetfFuel(0)
	end
	if (self.mem.engine_on) then
		self.mem.engine_on = nil
		self.car:StartEngine()
	end
	
	if (self.car:IsScopeEnable()) then
		if (self.mem.scope_num) then
			self.car:SetScopeActive(self.mem.scope_num)
			self.mem.scope_num = nil
		end
	end
	
	self:AttachUpdate()
end

function CDroneBinder:net_destroy()
	self:UpdateMapSpot(false)
	
	SendScriptCallback("drone_on_net",self.object,false)
	self.object:set_callback(callback.death,nil)
	self.object:set_callback(callback.net_spawn_after,nil)
	db.del_obj(self.object)
	del_object(self.object)
	object_binder.net_destroy(self)
end

function CDroneBinder:death_callback(obj,who)
	self:UpdateMapSpot(false)
	SendScriptCallback("drone_on_death",obj,who)
end

function CDroneBinder:net_save_relevant()
	return true
end

function CDroneBinder:save(packet)
	object_binder.save(self,packet)
	set_save_marker(packet,"save",false,"physics_binder")
	set_save_marker(packet,"save",true,"physics_binder")
	
	self.mem.engine_on = self.car:IsActiveEngine()
	if (self.car:IsScopeEnable()) then
		self.mem.scope_num = self.car:GetScopeActive()
	end
end

function CDroneBinder:load(packet)
	object_binder.load(self,packet)
	set_save_marker(packet,"load",false,"physics_binder")
	set_save_marker(packet,"load",true,"physics_binder")
end

--[[----------------------------------------------------------------------------------------------------
	Combat
------------------------------------------------------------------------------------------------------]]
DRONE_COMBAT_RANGE = math.pow(25,2)

function distance_xz_sqr(a,b)
	return a:position():distance_to_xz_sqr(b:position())
end

function firing_line_of_sight_clear(npc,obj)
	if (npc and obj) then
		local pos = utils_obj.safe_bone_pos(npc,"bip01_spine2")
		local dir = vector():sub(obj:center(),pos):normalize()
		local ray = ray_pick(pos,dir,100,3,npc)
		if (ray:query()) then
			local who = ray:get_object()
			if (who and (who:id() == obj:id())) then
				return true
			end
		end
	end
	return false
end

function validate(npc,vid)
	if (vid and vid < 4294967295 and npc:accessible(vid)) then 
		return (db.used_level_vertex_ids[vid] == nil) or (db.used_level_vertex_ids[vid] == npc:id())
	end 
	return false
end 

function best_enemy_drone(npc)
	local o = nil
	local d = DRONE_COMBAT_RANGE
	for oid,obj in pairs(db.drone_objects) do
		local dis = distance_xz_sqr(npc,obj)
		if (obj:alive() and obj:get_car():IsActiveEngine() and (d > dis)) then
			---[[
			if (true) then
				o = obj
				d = dis
			end
			--]]
			local mem = DRONE_MGR:StorageById(oid)
			if (mem and mem.owner_actor) and (npc:relation(db.actor) == game_object.enemy) then
				o = obj
				d = dis
			end
		end
	end
	return o
end

function can_npc_fight_drone(npc,obj)
	-- Using holder.
	if (npc:get_attached_vehicle()) then
		return false
	end
	-- Prioritize creature enemies if seeing them or they are closer.
	local ene = npc:best_enemy()
	if (ene) then
		if (npc:see(ene)) then
			return false
		end
		if (distance_xz_sqr(npc,ene) < distance_xz_sqr(npc,obj)) then
			return false
		end
	end
	return true
end

function on_npc_vs_heli_eva(self,heli)
	if (self.mod_flags) then
		return
	end
	
	local obj = best_enemy_drone(self.object)
	if (obj and can_npc_fight_drone(self.object,obj)) then
		self.ret_value = true
		self.mod_flags = URB_TAC:Name()
	end
end

function on_npc_vs_heli_act(self)
	if (self.st.mod_flags ~= URB_TAC:Name()) then
		return
	end
	self.ret_value = false

	local obj = best_enemy_drone(self.object)
	if not (obj) then
		return
	end
	
	local npc = self.object
	if (npc:path_type() ~= game_object.level_path) then
		npc:set_path_type(game_object.level_path)
	end
	
	local see = firing_line_of_sight_clear(npc,obj)
	local dir = vector():sub(obj:center(),utils_obj.safe_bone_pos(npc,"bip01_r_finger02"))
	
	if (self.st.vid) then
		-- Move to cover.
		if (npc:level_vertex_id() ~= self.st.vid) then
			local new_state = see and "raid_fire" or "raid"
			state_mgr.set_state(npc,new_state,nil,nil,{look_dir = dir},{fast_set = true})
			axr_npc_vs_heli.lmove(npc,self.st.vid,self.st)
			return
		end
		
		-- Stay at cover.
		local new_state = see and "threat_fire" or "threat"
		state_mgr.set_state(npc,new_state,nil,nil,{look_dir = dir},{fast_set = true})
		
		self.st.__keep_point_until = self.st.__keep_point_until or (time_global() + math.random(3000,8000))
		if (self.st.__keep_point_until > time_global()) then
			return
		end
		-- Change cover.
		self.st.__keep_point_until = nil
		db.used_level_vertex_ids[self.st.vid] = nil
		self.st.vid = nil
	end
	
	if (self:try_go_cover(npc,obj:position(),10) == nil) then
		self:try_to_strafe(npc)
	end
end


--[[----------------------------------------------------------------------------------------------------
	Registers
------------------------------------------------------------------------------------------------------]]
function on_game_start()
	_G.DRONE_MGR = CDroneManager()
end